import { prisma } from "./prisma";
import { createHereNowClient } from "./herenow";
import { logger } from "./logger";
import { calculateTrustScore } from "./trust";

export interface DailyReviewData {
  date: string;
  totalUsers: number;
  activeUsers: number;
  totalXp: number;
  topUsers: {
    username: string;
    xp: number;
    tier: string;
    trustScore: number;
  }[];
  newStamps: number;
  totalPayments: number;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function generateReviewHtml(data: DailyReviewData): string {
  const topRows = data.topUsers
    .map(
      (u, i) =>
        `<tr><td style="padding:8px 12px;border-bottom:1px solid #1e293b;color:#94a3b8">${i + 1}</td><td style="padding:8px 12px;border-bottom:1px solid #1e293b;color:#e2e8f0;font-weight:600">${escapeHtml(u.username)}</td><td style="padding:8px 12px;border-bottom:1px solid #1e293b;color:#22c55e;text-align:right">${u.xp.toLocaleString()}</td><td style="padding:8px 12px;border-bottom:1px solid #1e293b;color:#94a3b8;text-align:center">${escapeHtml(u.tier)}</td><td style="padding:8px 12px;border-bottom:1px solid #1e293b;color:#3b82f6;text-align:right">${u.trustScore}</td></tr>`
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>AxiomID Daily Review — ${escapeHtml(data.date)}</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{background:#0f172a;color:#e2e8f0;font-family:'Inter',system-ui,sans-serif;min-height:100vh;display:flex;align-items:center;justify-content:center;padding:24px}
.card{background:#1e293b;border:1px solid #334155;border-radius:16px;max-width:600px;width:100%;overflow:hidden}
.header{background:linear-gradient(135deg,#1e293b 0%,#0f172a 100%);padding:32px 24px;text-align:center;border-bottom:1px solid #334155}
.header h1{font-size:20px;font-weight:700;margin-bottom:4px}
.header .date{color:#94a3b8;font-size:14px}
.body{padding:24px}
.stats{display:grid;grid-template-columns:repeat(2,1fr);gap:16px;margin-bottom:24px}
.stat{background:#0f172a;border:1px solid #334155;border-radius:12px;padding:16px;text-align:center}
.stat-value{font-size:24px;font-weight:700;color:#3b82f6}
.stat-label{font-size:12px;color:#94a3b8;margin-top:4px}
.leaderboard h2{font-size:14px;color:#94a3b8;margin-bottom:8px;text-transform:uppercase;letter-spacing:0.05em}
table{width:100%;border-collapse:collapse}
.footer{padding:16px 24px;border-top:1px solid #334155;text-align:center;font-size:12px;color:#475569}
.footer a{color:#3b82f6;text-decoration:none}
</style>
</head>
<body>
<div class="card">
<div class="header">
<h1>AxiomID Daily Review</h1>
<div class="date">${escapeHtml(data.date)}</div>
</div>
<div class="body">
<div class="stats">
<div class="stat"><div class="stat-value">${data.totalUsers.toLocaleString()}</div><div class="stat-label">Total Users</div></div>
<div class="stat"><div class="stat-value">${data.activeUsers.toLocaleString()}</div><div class="stat-label">Active (24h)</div></div>
<div class="stat"><div class="stat-value">${data.totalXp.toLocaleString()}</div><div class="stat-label">Total XP</div></div>
<div class="stat"><div class="stat-value">${data.newStamps}</div><div class="stat-label">New Stamps</div></div>
</div>
${data.topUsers.length > 0 ? `<div class="leaderboard"><h2>Top Users</h2><table><tr><th style="padding:8px 12px;text-align:left;color:#94a3b8;font-size:12px">#</th><th style="padding:8px 12px;text-align:left;color:#94a3b8;font-size:12px">User</th><th style="padding:8px 12px;text-align:right;color:#94a3b8;font-size:12px">XP</th><th style="padding:8px 12px;text-align:center;color:#94a3b8;font-size:12px">Tier</th><th style="padding:8px 12px;text-align:right;color:#94a3b8;font-size:12px">Trust</th></tr>${topRows}</table></div>` : ""}
</div>
<div class="footer">Generated by <a href="https://axiomid.app">AxiomID</a> · ${escapeHtml(data.date)}</div>
</div>
</body>
</html>`;
}

export async function runDailyReview(): Promise<{ url: string }> {
  const now = new Date();
  const dateStr = now.toISOString().split("T")[0];

  const yesterday = new Date(now);
  yesterday.setDate(yesterday.getDate() - 1);

  const [totalUsers, activeUsers, recentPayments, newStamps] = await Promise.all([
    prisma.user.count(),
    prisma.user.count({
      where: { lastActive: { gte: yesterday } },
    }),
    prisma.piPayment.findMany({
      where: { createdAt: { gte: yesterday } },
      select: { amount: true },
    }),
    prisma.stamp.count({
      where: { createdAt: { gte: yesterday } },
    }),
  ]);

  const topUsers = await prisma.user.findMany({
    orderBy: { xp: "desc" },
    take: 10,
    select: {
      piUsername: true,
      xp: true,
      tier: true,
      did: true,
      walletAddress: true,
      stamps: { select: { id: true } },
    },
  });

  const reviewData: DailyReviewData = {
    date: dateStr,
    totalUsers,
    activeUsers,
    totalXp: topUsers.reduce((sum, u) => sum + u.xp, 0),
    topUsers: topUsers.map((u) => ({
      username: u.piUsername || u.walletAddress.slice(0, 10),
      xp: u.xp,
      tier: u.tier,
      trustScore: calculateTrustScore(u.xp, u.stamps.length),
    })),
    newStamps,
    totalPayments: recentPayments.length,
  };

  const html = generateReviewHtml(reviewData);

  const client = createHereNowClient();
  const { url } = await client.publishPage({
    title: `AxiomID Daily Review — ${dateStr}`,
    slug: `daily-review-${dateStr}`,
    html,
  });

  logger.info("[DAILY-REVIEW] Published daily review", { date: dateStr, url });

  return { url };
}
