"use client";

import React, { createContext, useContext, useState, useEffect, useRef, useCallback } from "react";

export type Language = "en" | "ar";

export const translations = {
  en: {
    // Navigation / Header
    nav_dashboard: "Dashboard",
    dashboard_title: "AxiomID Dashboard",
    nav_settings: "Settings",
    nav_status: "Network Status",
    nav_privacy: "Privacy Policy",
    nav_terms: "Terms of Service",
    connect_wallet: "Connect Pi Wallet",
    disconnect_wallet: "Disconnect",
    // Landing
    hero_title: "AxiomID",
    hero_heading: "Agent Identity for the AI Era.",
    hero_desc: "Your DID-based Agent Passport. Verify once, prove everywhere. KYA + KYC compliant identity for humans and their AI agents.",
    hero_subtitle: "The Human Authorization Protocol. Decentralized identity verification for human-AI collaboration.",
    hero_badge: "SECURE IDENTITY LAYER",
    btn_launch: "Launch Dashboard",
    btn_explorer: "Explore Protocol",
    stat_agents: "Registered Agents",
    stat_tx: "Total Transactions",
    stat_trust: "Average Trust Score",
    stat_users: "Active Users",
    // Dashboard
    welcome: "Welcome back",
    welcome_back: "Welcome back",
    your_passport: "Agent Passport",
    xp_balance: "XP Balance",
    trust_score: "Trust Score",
    tier: "Identity Tier",
    stamps_board: "Identity Stamps",
    claim_stamp: "Claim Stamp",
    stamps_desc: "Verify your credentials and links to claim cryptographic identity stamps.",
    connected: "Connected",
    not_connected: "Not Connected",
    agent_stats: "Agent Stats",
    skills: "Skills",
    quick_links: "Quick Links",
    identity_verification_kya: "Identity Verification (KYA)",
    skills_marketplace: "Skills Marketplace",
    create_your_agent: "Create Your Agent",
    agent_quick_actions: "Agent Quick Actions",
    replay_onboarding: "REPLAY ONBOARDING",
    demo_mode: "Demo Mode",
    demo_mode_desc: "Connect your wallet to claim actions and manage your agent.",
    // Settings
    settings_title: "Protocol Settings",
    settings_desc: "Manage your cryptographic credentials, linked accounts, and passport details.",
    linked_accounts: "Linked Platforms",
    credential_vc: "Verifiable Credential (VC)",
    view_vc: "View VC Payload",
    close: "Close",
    wallet_address: "Wallet Address",
    did: "Decentralized Identifier (DID)",
    system_appearance: "System Appearance",
    // Status
    status_title: "Network & Agent Status",
    status_desc: "Real-time protocol status and agent verification metrics.",
    operational: "Operational",
    system_all_good: "All systems are operating normally.",
    averages: "Averages & Rates",
    total_xp: "Total XP Earned",
    verification_rate: "Verification Success Rate",
    // Onboarding
    onboarding_title_1: "AxiomID Sovereign Protocol",
    onboarding_title_2: "AxiomID: The Soul Protocol",
    onboarding_title_3: "Your Passport is Ready!",
    onboarding_desc_1: "Establish your sovereign cryptographic proof of humanity. Link your credentials to gain trust points and earn stamps.",
    onboarding_desc_2: "Authorize autonomous agents to perform transactions on your behalf with safe-guards.",
    onboarding_desc_3: "Your Decentralized Identity (DID) and Agent Passport are active. Welcome to the root of trust.",
    onboarding_step_1: "Wallet Connection",
    onboarding_step_2: "Agent Creation",
    onboarding_step_3: "Ready",
    next: "Next",
    back: "Back",
    finish: "Get Started",
    // General
    loading: "Loading cryptographic context...",
    visitor: "Visitor",
    citizen: "Citizen",
    validator: "Validator",
    sovereign: "Sovereign",
    view_demo: "VIEW DEMO",
    enter_dashboard: "ENTER DASHBOARD",
    logout: "LOGOUT",
    connecting: "CONNECTING...",
    connect: "CONNECT",
    // Pi Browser prompts
    pi_browser_required: "Open this app from Pi Browser",
    pi_browser_demo_disabled: "Open this app from Pi Browser (Demo Disabled)",
    demo_disabled_desc: "Demo wallets are disabled for this deployment.",
    // Passport & Components
    agent_passport: "AGENT PASSPORT",
    no_address: "No address",
    label_wallet: "WALLET",
    label_agent: "AGENT",
    status_none: "NONE",
    tier_label: "TIER",
    label_trust: "TRUST",
    label_xp: "XP",
    label_issued: "ISSUED",
    kya_manifest: "KYA MANIFEST",
    manifest_principal: "Principal:",
    manifest_network: "Network:",
    pi_network: "Pi Network",
    manifest_kyc_bound: "KYC Bound:",
    manifest_license: "License:",
    passport_footer_verified: "AxiomID Verified • Pi Compatible Identity",
    trust_score_desc: "Earn stamps to build your cryptographic trust score.",
    stamps_label: "Stamps:",
    level_progress: "Level Progress",
    current_tier: "Current Tier:",
    percent_complete: "% Complete",
    next_tier: "Next Tier:",
    xp_needed: "XP needed",
    live_stamps_collection: "Live Stamps Collection",
    stamps_collection_desc: "Complete tasks to anchor verifiable credentials",
    w3c_vc_title: "W3C Verifiable Credential",
    w3c_vc_subtitle: "Cryptographically signed claim payload",
    copied: "COPIED!",
    copy_payload: "COPY PAYLOAD",
    download_json: "DOWNLOAD JSON",
    verified: "Verified",
    reward_label: "Reward:",
    claimed: "CLAIMED",
    inspect_vc: "INSPECT VC",
    placeholder_email: "Email address",
    placeholder_username: "Username / Handle",
    claiming: "CLAIMING...",
    submit: "SUBMIT",
    cancel: "CANCEL",
    connect_profile: "CONNECT PROFILE",
    score_excellent: "EXCELLENT",
    score_strong: "STRONG",
    score_moderate: "MODERATE",
    score_low: "LOW",
    score_new: "NEW",
    status_verified: "VERIFIED",
    status_pending: "PENDING",
    status_denied: "DENIED",
    passport_not_found: "Passport Not Found",
    passport_load_error: "Failed to load passport",
    create_your_passport: "CREATE YOUR PASSPORT",
    link_copied: "LINK COPIED!",
    share_passport: "SHARE PASSPORT",
    passport_verified_by: "This passport is verified by AxiomID Protocol",
    share_title: "AxiomID Agent Passport",
    share_text: "Check out my verified AxiomID Agent Passport!",
    vc_no_data: "No Verifiable Credential data available for this stamp.",
    vc_empty_metadata: "Credential metadata is empty.",
    vc_parse_error: "Failed to parse Verifiable Credential payload.",
    yes: "YES",
    no: "NO",
    settings_sovereign_title: "Sovereign Settings",
    settings_wallet_prompt: "Please connect your wallet to access profile details and link accounts.",
    settings_back_landing: "← Back to landing",
    settings_page_title: "AxiomID Settings",
    settings_page_desc: "Manage sovereign keys & connections",
    settings_dashboard_link: "← DASHBOARD",
    settings_profile_title: "Sovereign Profile",
    settings_pi_network_id: "PI NETWORK ID",
    settings_stellar_wallet: "STELLAR WALLET",
    settings_sovereign_did: "SOVEREIGN DID",
    settings_copy: "COPY",
    authenticated_pioneer: "Authenticated Pioneer",
    settings_identity_status: "IDENTITY STATUS (KYA)",
    settings_verified_human: "Verified Human",
    settings_pending_kyc: "Pending KYC Claim",
    settings_progression_title: "Progression & Experience",
    settings_social_title: "Verifiable Social Identifiers",
    settings_social_desc: "Bind your profiles to generate W3C compliance credentials signed cryptographically by the protocol authority.",
    settings_xp_reward: "XP Reward:",
    settings_connect_btn: "CONNECT",
    settings_ledger_title: "Cryptographic Action Ledger",
    settings_no_tx: "No transactions recorded in the local cache.",
    settings_tx_objective: "TX OBJECTIVE",
    settings_balance_shift: "BALANCE SHIFT",
    settings_timestamp: "TIMESTAMP",
    settings_link_profile: "Link {platform} Profile",
    settings_link_desc: "Type your username handle to build a verifiable social connection claim.",
    settings_link_handle_label: "Profile Handle",
    settings_link_email_label: "Email Address",
    settings_link_email_placeholder: "name@gmail.com",
    settings_link_placeholder: "@cryptojoker",
    settings_signing: "SIGNING...",
    settings_confirm_claim: "CONFIRM CLAIM",
    settings_vc_title: "SocialIdentityCredential (W3C Standard)",
    settings_vc_desc: "Signed by AxiomID issuer authority. Copy payload to verify portability.",
    // Dashboard Components
    welcome_back_name: "Welcome back, {username}",
    agent_identity_ready: "Your agent identity is ready. Level",
    demo_account: "Demo Account",
    demo_not_valid: "Not valid for production use",
    stat_level: "Level",
    stat_xp: "XP",
    stat_agent: "Agent",
    agent_trust_label: "Trust",
    stat_status: "Status",
    no_skills_installed: "No skills installed",
    kya_secure_did: "Secure your DID document by verifying your credentials.",
    kya_verified_anchored: "✓ AxiomID Verification Anchored",
    kya_identity_verified: "Your identity has been verified and permanently anchored under DID:",
    kya_verification_pending: "Verification Pending",
    kya_oracle_validating: "The oracle network is validating your credentials. Advanced tasks will unlock upon approval.",
    kya_pi_username: "Pi Username",
    kya_verifying: "VERIFYING...",
    kya_verify_identity: "VERIFY IDENTITY",
    agent_id_label: "Agent ID:",
    agent_xp_label: "XP",
    agent_last_active: "LAST ACTIVE",
    agent_never_active: "Never",
    agent_activating: "ACTIVATING...",
    agent_activate: "ACTIVATE",
    agent_pausing: "PAUSING...",
    agent_pause: "PAUSE",
    agent_resuming: "RESUMING...",
    agent_resume: "RESUME",
    terminal_title: "TERMINAL",
    terminal_entries: "entries",
    terminal_clear: "CLEAR",
    terminal_run_test: "RUN TEST",
    terminal_waiting: "Waiting for wallet activity...",
    view_passport: "View Passport",
    did_document: "DID Document",
    create_agent_title: "Create Your Agent",
    create_agent_desc: "Give your agent a name to get started.",
    create_agent_tier_info: "Your agent will begin at Tier 1 with 0 XP and can be activated anytime.",
    create_agent_placeholder: "Agent name (optional)",
    create_agent_creating: "CREATING...",
    create_agent_create: "CREATE",
  },
  ar: {
    // Navigation / Header
    nav_dashboard: "لوحة التحكم",
    dashboard_title: "لوحة تحكم AxiomID",
    nav_settings: "الإعدادات",
    nav_status: "حالة الشبكة",
    nav_privacy: "سياسة الخصوصية",
    nav_terms: "شروط الخدمة",
    connect_wallet: "ربط محفظة Pi",
    disconnect_wallet: "قطع الاتصال",
    // Landing
    hero_title: "AxiomID",
    hero_heading: "هوية العملاء لعصر الذكاء الاصطناعي.",
    hero_desc: "جواز العميل اللامركزي القائم على المعرفات اللامركزية DIDs. تحقق مرة واحدة، وأثبت هويتك في كل مكان. هوية متوافقة مع معايير KYA و KYC للبشر وعملائهم الآليين.",
    hero_subtitle: "بروتوكول تفويض الهوية البشرية. توثيق الهوية اللامركزية للتعاون المشترك بين البشر والذكاء الاصطناعي.",
    hero_badge: "طبقة الهوية المؤمنة",
    btn_launch: "تشغيل لوحة التحكم",
    btn_explorer: "استكشاف البروتوكول",
    stat_agents: "العملاء المسجلون",
    stat_tx: "إجمالي العمليات",
    stat_trust: "معدل نقاط الثقة",
    stat_users: "المستخدمون النشطون",
    // Dashboard
    welcome: "مرحباً بك مجدداً",
    welcome_back: "مرحباً بك مجدداً",
    your_passport: "جواز العميل",
    xp_balance: "رصيد نقاط XP",
    trust_score: "نقاط الثقة",
    tier: "فئة الهوية",
    stamps_board: "طوابع الهوية",
    claim_stamp: "المطالبة بالطابع",
    stamps_desc: "قم بتوثيق حساباتك وروابطك للمطالبة بطوابع الهوية التشفيرية.",
    connected: "متصل",
    not_connected: "غير متصل",
    agent_stats: "إحصائيات العميل",
    skills: "المهارات",
    quick_links: "روابط سريعة",
    identity_verification_kya: "توثيق الهوية (KYA)",
    skills_marketplace: "سوق المهارات",
    create_your_agent: "أنشئ عميلك الآلي",
    agent_quick_actions: "إجراءات العميل السريعة",
    replay_onboarding: "إعادة عرض الترحيب",
    demo_mode: "وضع العرض التجريبي",
    demo_mode_desc: "قم بربط محفظتك للمطالبة بالعمليات وإدارة عميلك الآلي.",
    // Settings
    settings_title: "إعدادات البروتوكول",
    settings_desc: "إدارة المؤهلات التشفيرية، الحسابات المرتبطة، وتفاصيل الجواز الخاص بك.",
    linked_accounts: "المنصات المرتبطة",
    credential_vc: "الوثيقة القابلة للتحقق (VC)",
    view_vc: "عرض تفاصيل الوثيقة (VC)",
    close: "إغلاق",
    wallet_address: "عنوان المحفظة",
    did: "المعرف اللامركزي (DID)",
    system_appearance: "مظهر النظام",
    // Status
    status_title: "حالة الشبكة والعميل",
    status_desc: "مؤشرات حالة البروتوكول المباشرة ومقاييس توثيق العملاء.",
    operational: "يعمل بشكل طبيعي",
    system_all_good: "جميع الأنظمة تعمل بشكل طبيعي وآمن.",
    averages: "المعدلات والنسب",
    total_xp: "إجمالي نقاط XP المكتسبة",
    verification_rate: "نسبة توثيق الهوية الناجحة",
    // Onboarding
    onboarding_title_1: "بروتوكول AxiomID السيادي",
    onboarding_title_2: "AxiomID: بروتوكول الروح",
    onboarding_title_3: "جواز سفرك أصبح جاهزاً!",
    onboarding_desc_1: "أنشئ دليلك التشفيري السيادي على بشريتك. اربط حساباتك للحصول على نقاط ثقة وطوابع تشفيرية.",
    onboarding_desc_2: "قم بتفويض عملاء مستقلين لإجراء المعاملات نيابة عنك بحماية أمنية كاملة.",
    onboarding_desc_3: "المعرف اللامركزي (DID) وجواز العميل الخاص بك نشط الآن. أهلاً بك في جذر الثقة.",
    onboarding_step_1: "ربط المحفظة",
    onboarding_step_2: "إنشاء العميل",
    onboarding_step_3: "جاهز",
    next: "التالي",
    back: "السابق",
    finish: "ابدأ الآن",
    // General
    loading: "جاري تحميل الهوية التشفيرية...",
    visitor: "زائر",
    citizen: "مواطن",
    validator: "مدقق",
    sovereign: "سيادي",
    view_demo: "عرض العرض التجريبي",
    enter_dashboard: "دخول لوحة التحكم",
    logout: "تسجيل الخروج",
    connecting: "جاري الاتصال...",
    connect: "اتصال",
    // Pi Browser prompts
    pi_browser_required: "افتح التطبيق من Pi Browser",
    pi_browser_demo_disabled: "افتح التطبيق من Pi Browser (التجربة معطلة)",
    demo_disabled_desc: "المحافظ التجريبية معطلة في هذا الإصدار.",
    // Passport & Components
    agent_passport: "جواز العميل",
    no_address: "لا يوجد عنوان",
    label_wallet: "المحفظة",
    label_agent: "العميل",
    status_none: "لا شيء",
    tier_label: "الفئة",
    label_trust: "الثقة",
    label_xp: "نقاط XP",
    label_issued: "صادر",
    kya_manifest: "بيان KYA",
    manifest_principal: "المسؤول:",
    manifest_network: "الشبكة:",
    pi_network: "شبكة Pi",
    manifest_kyc_bound: "مرتبط بـ KYC:",
    manifest_license: "الرخصة:",
    passport_footer_verified: "موثق من AxiomID • هوية متوافقة مع Pi",
    trust_score_desc: "اجمع الطوابع لبناء نقاط ثقة تشفيرية.",
    stamps_label: "الطوابع:",
    level_progress: "تقدم المستوى",
    current_tier: "الفئة الحالية:",
    percent_complete: "% مكتمل",
    next_tier: "الفئة التالية:",
    xp_needed: "نقاط XP مطلوبة",
    live_stamps_collection: "مجموعة الطوابع المباشرة",
    stamps_collection_desc: "أكمل المهام لتقسيم بيانات اعتماد قابلة للتحقق",
    w3c_vc_title: "وثيقة اعتماد W3C القابلة للتحقق",
    w3c_vc_subtitle: "مطالبة موقعة تشفيرياً",
    copied: "تم النسخ!",
    copy_payload: "نسخ المحتوى",
    download_json: "تحميل JSON",
    verified: "موثق",
    reward_label: "المكافأة:",
    claimed: "تم المطالبة",
    inspect_vc: "فحص الوثيقة",
    placeholder_email: "البريد الإلكتروني",
    placeholder_username: "اسم المستخدم",
    claiming: "جاري المطالبة...",
    submit: "إرسال",
    cancel: "إلغاء",
    connect_profile: "ربط الحساب",
    score_excellent: "ممتاز",
    score_strong: "قوي",
    score_moderate: "متوسط",
    score_low: "منخفض",
    score_new: "جديد",
    status_verified: "موثق",
    status_pending: "قيد المراجعة",
    status_denied: "مرفوض",
    passport_not_found: "جواز السفر غير موجود",
    passport_load_error: "فشل تحميل الجواز",
    create_your_passport: "أنشئ جواز سفرك",
    link_copied: "تم نسخ الرابط!",
    share_passport: "مشاركة الجواز",
    passport_verified_by: "هذا الجواز موثق من بروتوكول AxiomID",
    share_title: "جواز العميل AxiomID",
    share_text: "تحقق من جواز العميل AxiomID الموثق الخاص بي!",
    vc_no_data: "لا توجد بيانات وثيقة قابلة للتحقق لهذا الطابع.",
    vc_empty_metadata: "بيانات الوثيقة فارغة.",
    vc_parse_error: "فشل في تحليل بيانات الوثيقة القابلة للتحقق.",
    yes: "نعم",
    no: "لا",
    settings_sovereign_title: "إعدادات السيادة",
    settings_wallet_prompt: "يرجى ربط محفظتك للوصول إلى تفاصيل الملف الشخصي وربط الحسابات.",
    settings_back_landing: "← العودة إلى الصفحة الرئيسية",
    settings_page_title: "إعدادات AxiomID",
    settings_page_desc: "إدارة المفاتيح السيادية والاتصالات",
    settings_dashboard_link: "← لوحة التحكم",
    settings_profile_title: "الملف السيادي",
    settings_pi_network_id: "معرف شبكة Pi",
    settings_stellar_wallet: "محفظة Stellar",
    settings_sovereign_did: "المعرف اللامركزي السيادي",
    settings_copy: "نسخ",
    authenticated_pioneer: "رائد موثق",
    settings_identity_status: "حالة الهوية (KYA)",
    settings_verified_human: "إنسان موثق",
    settings_pending_kyc: "مطالبة KYC معلقة",
    settings_progression_title: "التقدم والخبرة",
    settings_social_title: "المعرفات الاجتماعية القابلة للتحقق",
    settings_social_desc: "اربط حساباتك لإنشاء بيانات اعتماد W3C موقعة تشفيرياً من سلطة البروتوكول.",
    settings_xp_reward: "مكافأة XP:",
    settings_connect_btn: "اتصال",
    settings_ledger_title: "سجل الإجراءات التشفيري",
    settings_no_tx: "لا توجد معاملات مسجلة في الذاكرة المؤقتة.",
    settings_tx_objective: "الهدف",
    settings_balance_shift: "تغير الرصيد",
    settings_timestamp: "الوقت",
    settings_link_profile: "ربط حساب {platform}",
    settings_link_desc: "اكتب اسم المستخدم لإنشاء مطالبة اتصال اجتماعي قابلة للتحقق.",
    settings_link_handle_label: "اسم المستخدم",
    settings_link_email_label: "البريد الإلكتروني",
    settings_link_email_placeholder: "name@gmail.com",
    settings_link_placeholder: "@cryptojoker",
    settings_signing: "جاري التوقيع...",
    settings_confirm_claim: "تأكيد المطالبة",
    settings_vc_title: "SocialIdentityCredential (معيار W3C)",
    settings_vc_desc: "موقع من سلطة إصدار AxiomID. انسخ المحتوى للتحقق من قابلية النقل.",
    // Dashboard Components
    welcome_back_name: "مرحباً بك مجدداً، {username}",
    agent_identity_ready: "هوية عميلك جاهزة. المستوى",
    demo_account: "حساب تجريبي",
    demo_not_valid: "غير صالح للاستخدام في الإنتاج",
    stat_level: "المستوى",
    stat_xp: "نقاط XP",
    stat_agent: "العميل",
    agent_trust_label: "الثقة",
    stat_status: "الحالة",
    no_skills_installed: "لا توجد مهارات مثبتة",
    kya_secure_did: "أمنت مستند DID الخاص بك من خلال التحقق من بياناتك.",
    kya_verified_anchored: "✓ تم توثيق AxiomID",
    kya_identity_verified: "تم التحقق من هويتك وتوثيقها بشكل دائم تحت المعرف:",
    kya_verification_pending: "التوثيق معلق",
    kya_oracle_validating: "شبكة الأوراكل تتحقق من بياناتك. سيتم فتح المهام المتقدمة بعد الموافقة.",
    kya_pi_username: "اسم مستخدم Pi",
    kya_verifying: "جاري التوثيق...",
    kya_verify_identity: "توثيق الهوية",
    agent_id_label: "معرف العميل:",
    agent_xp_label: "نقاط XP",
    agent_last_active: "آخر نشاط",
    agent_never_active: "لم يكن نشطاً",
    agent_activating: "جاري التنشيط...",
    agent_activate: "تنشيط",
    agent_pausing: "جاري الإيقاف المؤقت...",
    agent_pause: "إيقاف مؤقت",
    agent_resuming: "جاري الاستئناف...",
    agent_resume: "استئناف",
    terminal_title: "الطرفية",
    terminal_entries: "سجلات",
    terminal_clear: "مسح",
    terminal_run_test: "تشغيل اختبار",
    terminal_waiting: "في انتظار نشاط المحفظة...",
    view_passport: "عرض الجواز",
    did_document: "مستند DID",
    create_agent_title: "أنشئ عميلك",
    create_agent_desc: "أعطِ عميلك اسماً للبدء.",
    create_agent_tier_info: "سيبدأ عميلك من الفئة 1 مع 0 نقطة XP ويمكن تنشيطه في أي وقت.",
    create_agent_placeholder: "اسم العميل (اختياري)",
    create_agent_creating: "جاري الإنشاء...",
    create_agent_create: "إنشاء",
  }
};

type TranslationsKey = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationsKey | string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

/**
 * Provides language selection, persistence, and a translation helper to descendant components.
 *
 * Persists the chosen language to localStorage under `aix_language` and updates
 * `document.documentElement.dir` and `document.documentElement.lang` after initial mount.
 *
 * @param children - React nodes that will receive the language context
 * @returns A React context provider that supplies `{ language, setLanguage, t }` to its descendants
 */
export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === "undefined") return "en";
    const saved = localStorage.getItem("aix_language") as Language;
    return saved === "en" || saved === "ar" ? saved : "en";
  });
  const mountedRef = useRef(false);

  useEffect(() => {
    mountedRef.current = true;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("aix_language", lang);
  }, []);

  const t = useCallback((key: string): string => {
    const dict = translations[language] || translations.en;
    return (dict as Record<string, string>)[key] || key;
  }, [language]);

  const value = React.useMemo(
    () => ({ language, setLanguage, t }),
    [language, setLanguage, t]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

/**
 * Access the language context value for the current React tree.
 *
 * @returns The context object with `language`, `setLanguage`, and `t` (translation) helpers.
 * @throws Error if called outside a `LanguageProvider` (message: "useLanguage must be used within a LanguageProvider").
 */
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
