"use client";

import React, { createContext, useContext, useState, useEffect, useRef, useCallback } from "react";

export type Language = "en" | "ar";

export const translations = {
  en: {
    // Navigation / Header
    nav_dashboard: "Dashboard",
    dashboard_title: "AxiomID Dashboard",
    nav_settings: "Settings",
    nav_status: "Network Status",
    nav_privacy: "Privacy Policy",
    nav_terms: "Terms of Service",
    nav_explorer: "Protocol Explorer",
    nav_docs: "Documentation",
    nav_about: "Roadmap & About",
    nav_leaderboard: "Leaderboard",
    nav_onboarding: "Onboarding",
    connect_wallet: "Connect Pi Wallet",
    disconnect_wallet: "Disconnect",
    // Landing
    hero_title: "AxiomID",
    hero_heading: "Agent Identity for the AI Era.",
    hero_desc: "Your DID-based Agent Passport. Verify once, prove everywhere. KYA + KYC compliant identity for humans and their AI agents.",
    hero_subtitle: "The Human Authorization Protocol. Decentralized identity verification for human-AI collaboration.",
    hero_badge: "SECURE IDENTITY LAYER",
    btn_launch: "Launch Dashboard",
    btn_explorer: "Explore Protocol",
    stat_agents: "Registered Agents",
    stat_tx: "Total Transactions",
    stat_trust: "Average Trust Score",
    stat_users: "Active Users",
    // Dashboard
    welcome: "Welcome back",
    welcome_back: "Welcome back",
    your_passport: "Agent Passport",
    xp_balance: "XP Balance",
    trust_score: "Trust Score",
    tier: "Identity Tier",
    stamps_board: "Identity Stamps",
    claim_stamp: "Claim Stamp",
    stamps_desc: "Verify your credentials and links to claim cryptographic identity stamps.",
    connected: "Connected",
    not_connected: "Not Connected",
    agent_stats: "Agent Stats",
    skills: "Skills",
    quick_links: "Quick Links",
    identity_verification_kya: "Identity Verification (KYA)",
    skills_marketplace: "Skills Marketplace",
    marketplace: "Marketplace",
    sandbox: "Sandbox",
    create_your_agent: "Create Your Agent",
    agent_quick_actions: "Agent Quick Actions",
    replay_onboarding: "REPLAY ONBOARDING",
    // Settings
    settings_title: "Protocol Settings",
    settings_desc: "Manage your cryptographic credentials, linked accounts, and passport details.",
    linked_accounts: "Linked Platforms",
    credential_vc: "Verifiable Credential (VC)",
    view_vc: "View VC Payload",
    close: "Close",
    wallet_address: "Wallet Address",
    did: "Decentralized Identifier (DID)",
    system_appearance: "System Appearance",
    // Status
    status_title: "Network & Agent Status",
    status_desc: "Real-time protocol status and agent verification metrics.",
    operational: "Operational",
    system_all_good: "All systems are operating normally.",
    averages: "Averages & Rates",
    total_xp: "Total XP Earned",
    verification_rate: "Verification Success Rate",
    // Onboarding
    onboarding_title_1: "AxiomID Sovereign Protocol",
    onboarding_title_2: "AxiomID: The Soul Protocol",
    onboarding_title_3: "Your Passport is Ready!",
    onboarding_desc_1: "Establish your sovereign cryptographic proof of humanity. Link your credentials to gain trust points and earn stamps.",
    onboarding_desc_2: "Authorize autonomous agents to perform transactions on your behalf with safe-guards.",
    onboarding_desc_3: "Your Decentralized Identity (DID) and Agent Passport are active. Welcome to the root of trust.",
    onboarding_step_1: "Wallet Connection",
    onboarding_step_2: "Agent Creation",
    onboarding_step_3: "Ready",
    onboarding_step_label: "STEP {step} OF 4",
    onboarding_step1_title: "Link Sovereign Key",
    onboarding_step1_desc: "Establish authorization link via Stellar or Pi Network protocol key.",
    onboarding_step2_title: "Configure Your Agent",
    onboarding_step2_desc: "Give your autonomous agent representative a custom profile label.",
    onboarding_step3_title: "Anchor Trust Status",
    onboarding_step3_desc: "Acquire W3C social credentials and complete the basic human oracle verifications.",
    onboarding_step4_title: "Identity Provisioned",
    onboarding_step4_desc: "Your decentralized agent passport is fully anchored on the registry.",
    onboarding_connect_desc: "Authorize access to fetch metadata: user identifier, wallet keys, and active nodes settings.",
    onboarding_wallet_connected: "Wallet connected successfully.",
    onboarding_requesting_access: "Requesting Pi Browser access...",
    onboarding_connect_wallet_btn: "CONNECT WALLET",
    onboarding_agent_name_label: "Agent Representative Name",
    onboarding_agent_name_placeholder: "e.g. Sentinel-1",
    onboarding_provisioning: "PROVISIONING AGENT...",
    onboarding_provision_btn: "PROVISION AGENT",
    onboarding_seal_desc: "Acquiring the basic credential stamp validates KYA parameters directly to secure trust delegation limits.",
    onboarding_seal_verified: "Sovereign DID resolution verified. ready to seal.",
    onboarding_seal_btn: "SEAL PASSPORT DATA",
    onboarding_congrats_desc: "Congratulations, Pioneer! Your passport profile is verified, cryptographically signed, and portable as did:axiom standard metadata.",
    onboarding_enter_dashboard: "ENTER DASHBOARD",
    onboarding_back: "\u2190 BACK",
    onboarding_footer: "\u00a9 2026 AxiomID Protocol \u2022 Sovereign Onboarding wizard",
    onboarding_agent_failed: "Failed to provision agent. Please try again.",
    onboarding_state_prefix: "STATE: ",
    onboarding_state_visitor: "VISITOR",
    onboarding_state_connected: "CONNECTED",
    onboarding_state_partial_kyc: "PARTIAL KYC",
    onboarding_state_verified: "VERIFIED",
    onboarding_state_pending_review: "PENDING REVIEW",
    onboarding_state_error: "ERROR",
    onboarding_default_agent_name: "Axiom Pioneer Agent",
    header_back: "BACK",
    passport_locked_preview: "LOCKED PREVIEW",
    passport_anonymous: "Anonymous Pioneer",
    next: "Next",
    back: "Back",
    finish: "Get Started",
    // General
    loading: "Loading cryptographic context...",
    visitor: "Visitor",
    citizen: "Citizen",
    validator: "Validator",
    sovereign: "Sovereign",
    enter_dashboard: "ENTER DASHBOARD",
    logout: "LOGOUT",
    connecting: "CONNECTING...",
    connect: "CONNECT",
    claim_passport: "Claim Your Passport",
    open_dashboard: "Open Dashboard",
    read_docs: "Read Docs",
    backed_by_pi: "Backed by Pi Network",
    pioneers_joined: "Pioneers Joined",
    agents_deployed: "Agents Deployed",
    on_chain: "100% On-chain",
    tab_passport: "Passport",
    tab_actions: "Actions",
    tab_agent: "Agent",
    tab_terminal: "Terminal",
    tab_marketplace: "Marketplace",
    ad_rewards_title: "REWARDED PI ADS",
    ad_rewards_desc: "Watch a short ad to earn +10 XP immediately and upgrade your authorization tier.",
    ad_rewards_loading: "LOADING...",
    ad_rewards_btn: "WATCH AD (+10 XP)",
    watch_demo_title: "See It In Action",
    watch_demo_desc: "Watch how AxiomID creates your sovereign identity in seconds.",
    quick_stats: "Quick Stats",
    days_active: "Days Active",
    recent_activity: "Recent Activity",
    actions_count: "Actions",
    trust_score_label: "Trust Score",
    xp_progress: "XP Progress",
    agent_status: "Agent Status",
    no_activity: "No recent activity",
    // Pi Browser prompts
    pi_browser_required: "Connect Pi Browser to unlock your identity",
    // Passport & Components
    agent_passport: "AGENT PASSPORT",
    no_address: "No address",
    label_wallet: "WALLET",
    label_agent: "AGENT",
    status_none: "NONE",
    tier_label: "TIER",
    label_trust: "TRUST",
    label_xp: "XP",
    label_issued: "ISSUED",
    kya_manifest: "KYA MANIFEST",
    manifest_principal: "Principal:",
    manifest_network: "Network:",
    pi_network: "Pi Network",
    manifest_kyc_bound: "KYC Bound:",
    manifest_license: "License:",
    passport_footer_verified: "AxiomID Verified • Pi Compatible Identity",
    trust_score_desc: "Earn stamps to build your cryptographic trust score.",
    stamps_label: "Stamps:",
    level_progress: "Level Progress",
    current_tier: "Current Tier:",
    percent_complete: "% Complete",
    next_tier: "Next Tier:",
    xp_needed: "XP needed",
    live_stamps_collection: "Live Stamps Collection",
    stamps_collection_desc: "Complete tasks to anchor verifiable credentials",
    w3c_vc_title: "W3C Verifiable Credential",
    w3c_vc_subtitle: "Cryptographically signed claim payload",
    copied: "COPIED!",
    copy_payload: "COPY PAYLOAD",
    download_json: "DOWNLOAD JSON",
    verified: "Verified",
    reward_label: "Reward:",
    claimed: "CLAIMED",
    inspect_vc: "INSPECT VC",
    placeholder_email: "Email address",
    placeholder_username: "Username / Handle",
    claiming: "CLAIMING...",
    submit: "SUBMIT",
    cancel: "CANCEL",
    connect_profile: "CONNECT PROFILE",
    score_excellent: "EXCELLENT",
    score_strong: "STRONG",
    score_moderate: "MODERATE",
    score_low: "LOW",
    score_new: "NEW",
    status_verified: "VERIFIED",
    status_pending: "PENDING",
    status_unverified: "UNVERIFIED",
    status_denied: "DENIED",
    passport_not_found: "Passport Not Found",
    passport_not_found_description: "This passport doesn't exist or has been removed.",
    passport_load_error: "Failed to load passport",
    something_went_wrong: "Something went wrong",
    try_again: "TRY AGAIN",
    signin_failed: "Sign-in failed",
    completing_sign_in: "Completing sign-in...",
    create_your_passport: "CREATE YOUR PASSPORT",
    link_copied: "LINK COPIED!",
    share_passport: "SHARE PASSPORT",
    export_image: "Export as Image",
    mint_sbt: "Mint as SBT",
    mint_success: "Soulbound Token minted successfully on Stellar!",
    passport_verified_by: "This passport is verified by AxiomID Protocol",
    passport_export_failed: "Failed to export passport image. Please try again.",
    share_title: "AxiomID Agent Passport",
    share_text: "Check out my verified AxiomID Agent Passport!",
    vc_no_data: "No Verifiable Credential data available for this stamp.",
    vc_empty_metadata: "Credential metadata is empty.",
    vc_parse_error: "Failed to parse Verifiable Credential payload.",
    yes: "YES",
    no: "NO",
    settings_sovereign_title: "Sovereign Settings",
    settings_wallet_prompt: "Please connect your wallet to access profile details and link accounts.",
    settings_back_landing: "← Back to landing",
    settings_page_title: "AxiomID Settings",
    settings_page_desc: "Manage sovereign keys & connections",
    settings_dashboard_link: "← DASHBOARD",
    settings_profile_title: "Your Profile",
    settings_pi_network_id: "PI NETWORK ID",
    settings_stellar_wallet: "STELLAR WALLET",
    settings_sovereign_did: "YOUR DID",
    settings_copy: "COPY",
    authenticated_pioneer: "Authenticated Pioneer",
    settings_identity_status: "IDENTITY STATUS",
    settings_verified_human: "Verified Human",
    settings_pending_kyc: "Pending Verification",
    settings_progression_title: "Your Progress",
    settings_social_title: "Connected Accounts",
    settings_xp_reward: "XP Reward:",
    settings_connect_btn: "CONNECT",
    settings_ledger_title: "Activity History",
    settings_ledger_empty_helper: "Connect accounts or claim stamps to see activity here.",
    settings_disconnect_btn: "Disconnect",
    settings_no_tx: "No activity yet. Your actions will appear here as you use AxiomID.",
    settings_tx_objective: "TX OBJECTIVE",
    settings_balance_shift: "BALANCE SHIFT",
    settings_timestamp: "TIMESTAMP",
    settings_link_profile: "Link {platform} Profile",
    settings_link_desc: "Type your username to connect this account. This creates a verified link that proves you own both accounts.",
    settings_link_handle_label: "Profile Handle",
    settings_link_email_label: "Email Address",
    settings_link_email_placeholder: "name@gmail.com",
    settings_link_placeholder: "@cryptojoker",
    settings_signing: "SIGNING...",
    settings_confirm_claim: "CONFIRM CLAIM",
    settings_vc_title: "SocialIdentityCredential (W3C Standard)",
    settings_vc_desc: "Signed by AxiomID issuer authority. Copy payload to verify portability.",
    settings_profile_helper: "This is how others see you on AxiomID. Your wallet address and DID are your unique identity.",
    settings_progression_helper: "Earn XP by completing tasks, connecting accounts, and using your agent. Higher tiers unlock more features.",
    settings_social_helper: "Linking accounts helps prove you're a real person and earns you XP. Each connection creates a cryptographic proof.",
    settings_ledger_helper: "A record of all your actions on AxiomID. Every stamp claim, account link, and skill install is recorded here.",
    settings_danger_zone: "Danger Zone",
    settings_danger_desc: "These actions are permanent and cannot be undone.",
    settings_export_data: "Export Data",
    settings_export_desc: "Download a copy of your passport data, stamps, and activity history as JSON.",
    settings_export_btn: "EXPORT JSON",
    settings_sidebar_profile: "Profile",
    settings_sidebar_accounts: "Linked Accounts",
    settings_sidebar_ledger: "XP Ledger",
    settings_sidebar_settings: "Settings",
    settings_confirm_title: "Are you sure?",
    settings_confirm_disconnect: "This will disconnect your {platform} account. You'll lose the XP from this connection.",
    settings_confirm_action: "Confirm",
    settings_confirm_cancel: "Cancel",
    settings_disconnecting: "Disconnecting...",
    settings_vc_copied: "VC payload copied to clipboard",
    settings_disconnect_failed: "Failed to disconnect account",
    settings_progress_label: "Progress",
    settings_max_level: "MAX LEVEL ACHIEVED",
    settings_xp_needed: "XP NEEDED",
    // Dashboard Showcase Mode
    showcase_title: "Showcase Mode",
    showcase_desc: "Establish a secure human-AI delegation link. Once authenticated inside the Pi Browser, this dashboard unlocks real-time transaction guards, live oracles, and social stamp bindings.",
    // Marketplace toasts / errors
    marketplace_install_success: "Skill installed successfully",
    marketplace_need_agent: "Create an agent before purchasing skills",
    // Dashboard Components
    welcome_back_name: "Welcome back, {username}",
    agent_identity_ready: "Your agent identity is ready. Level",
    stat_level: "Level",
    stat_xp: "XP",
    stat_agent: "Agent",
    agent_trust_label: "Trust",
    stat_status: "Status",
    no_skills_installed: "No skills installed",
    kya_secure_did: "Secure your DID document by verifying your credentials.",
    kya_verified_anchored: "✓ AxiomID Verification Anchored",
    kya_identity_verified: "Your identity has been verified and permanently anchored under DID:",
    kya_verification_pending: "Verification Pending",
    kya_oracle_validating: "The oracle network is validating your credentials. Advanced tasks will unlock upon approval.",
    kya_pi_username: "Pi Username",
    kya_verifying: "VERIFYING...",
    kya_verify_identity: "VERIFY KYC",
    agent_id_label: "Agent ID:",
    agent_xp_label: "XP",
    agent_last_active: "LAST ACTIVE",
    agent_never_active: "Never",
    agent_activating: "ACTIVATING...",
    agent_activate: "ACTIVATE",
    agent_pausing: "PAUSING...",
    agent_pause: "PAUSE",
    agent_resuming: "RESUMING...",
    agent_resume: "RESUME",
    terminal_title: "TERMINAL",
    terminal_entries: "entries",
    terminal_clear: "CLEAR",
    terminal_run_test: "RUN TEST",
    terminal_waiting: "Waiting for wallet activity...",
    view_passport: "View Passport",
    did_document: "DID Document",
    create_agent_title: "Create Your Agent",
    create_agent_desc: "Give your agent a name to get started.",
    create_agent_tier_info: "Your agent will begin at Tier 1 with 0 XP and can be activated anytime.",
    create_agent_placeholder: "Agent name (optional)",
    create_agent_creating: "CREATING...",
    create_agent_create: "CREATE",
    // Privacy page
    privacy_legal: "LEGAL",
    privacy_last_updated: "Last updated: May 17, 2026",
    privacy_title: "Privacy",
    privacy_title_gradient: "Policy",
    privacy_subtitle: "How AxiomID handles your data.",
    privacy_info_collect: "Information We Collect",
    privacy_info_collect_desc: "When you connect your wallet via Pi Network, we collect your Pi wallet address and Pi Network UID for the purpose of authentication and XP tracking. We do not collect personal identifiable information such as your name, email, or IP address beyond standard server logs.",
    privacy_how_use: "How We Use Information",
    privacy_how_use_desc: "We use your wallet address and Pi UID solely to operate the App, track reputation scores (XP/Tier), and enable AI agent verification. Your data is never sold or shared with third parties. Aggregated, anonymized analytics may be used for platform improvement.",
    privacy_data_storage: "Data Storage & Security",
    privacy_data_storage_desc: "Your data is stored securely in our PostgreSQL database on Ghost infrastructure. We implement industry-standard encryption at rest and in transit. You may request deletion of your data at any time by contacting us via GitHub.",
    privacy_rights: "Your Rights",
    privacy_rights_desc: "You have the right to access, correct, or delete your data. To exercise these rights, open an issue on our GitHub repository or reach out to the developer directly.",
    // Terms page
    terms_legal: "LEGAL",
    terms_last_updated: "Last updated: May 17, 2026",
    terms_title: "Terms of Service",
    terms_title_main: "Terms of",
    terms_title_highlight: "Service",
    terms_subtitle: "By using AxiomID, you agree to these terms.",
    terms_use: "Use of Service",
    terms_use_desc: "AxiomID provides decentralized identity verification and reputation tracking. You may use the service in compliance with all applicable laws and regulations. The service is provided for lawful purposes only.",
    terms_wallet: "Wallet Connection",
    terms_wallet_desc: "Connecting your Pi wallet is required for authentication. You are solely responsible for maintaining the security of your wallet and private keys. AxiomID never has access to your private keys or seed phrases.",
    terms_ai_agent: "AI Agent Verification",
    terms_ai_agent_desc: "Each user may register one verified AI agent. The verified agent may interact with ecosystem products on your behalf. You are responsible for all actions taken by your agent. Agent verification is non-transferable.",
    terms_liability: "Limitation of Liability",
    terms_liability_desc: "The App is provided \"as is\" without warranties of any kind, either express or implied. We are not liable for any damages arising from the use or inability to use the service, including but not limited to loss of reputation score, agent data, or Pi transactions.",
    terms_changes: "Changes to Terms",
    terms_changes_desc: "We may update these terms at any time. Continued use of the service after changes constitutes acceptance of the new terms. You will be notified of material changes via the app.",
    // Status page
    status_network_title: "Network Status",
    status_network_desc: "Real-time monitoring of AxiomID protocol and agent network",
    status_retry: "RETRY",
    status_registered_agents: "Verified Agents",
    status_active_onchain: "People who have joined the network",
    status_total_transactions: "Payments Made",
    status_pi_payments: "Pi payments processed safely",
    status_avg_trust: "Community Trust",
    status_network_safety: "How much the community trusts the network",
    status_active_agents: "Online Now",
    status_executing_loops: "Agents currently active",
    status_total_xp: "Points Earned",
    status_accumulated: "Total reputation points collected",
    status_verification_rate: "Verification Success",
    status_kyc_index: "Percentage of users who passed verification",
    status_protocol_details: "Network Info",
    status_network: "Network",
    status_version: "Version",
    status_refreshed: "Refreshed",
    status_ago: "s ago",
    status_service_health: "System Status",
    status_uptime: "UPTIME",
    status_manifest_api: "Agent Identity",
    status_manifest_desc: "Every agent has a public identity card. You can look up any agent's verified profile using their username.",
    status_get: "GET",
    status_unable_load: "Unable to Load Status",
    status_could_not_fetch: "Could not fetch network statistics. Please try again later.",
    status_no_data: "No data available yet",
    status_no_data_desc: "Network statistics will appear here once agents start joining.",
    // Sandbox page
    sandbox_title: "Test Area",
    sandbox_active: "SANDBOX ACTIVE",
    sandbox_idle: "ENGINE IDLE",
    sandbox_edit_manifest: "Edit Rules",
    sandbox_ast_preview: "Preview Structure",
    sandbox_yaml_md: "Rules Format",
    sandbox_syntax_tree: "Structure View",
    sandbox_input_payload: "Test Data",
    sandbox_parameters: "Parameters",
    sandbox_running: "RUNNING SIMULATION...",
    sandbox_run_test: "Run Test",
    sandbox_copy_payload: "COPY PAYLOAD",
    sandbox_terminal_output: "Results",
    sandbox_waiting: "Click \"Run Test\" to see results here",
    sandbox_security_scan: "Safety Check",
    sandbox_pending: "Pending",
    sandbox_scanning: "Scanning",
    sandbox_passed: "PASSED",
    sandbox_failed: "FAILED",
    sandbox_sandbox_isolation: "Safe Environment",
    sandbox_sandbox_desc: "Runs in an isolated, secure container.",
    sandbox_ast_analysis: "Structure Check",
    sandbox_ast_desc: "Scans for harmful content in your rules.",
    sandbox_injection_guard: "Input Safety",
    sandbox_injection_desc: "Makes sure inputs can't break the system.",
    sandbox_signature_anchor: "Creator Verified",
    sandbox_signature_desc: "Confirms the creator's identity is confirmed.",
    sandbox_exfil_scan: "Network Safety",
    sandbox_exfil_desc: "Blocks any unauthorised data sharing.",
    sandbox_command_block: "Dangerous Commands Blocked",
    sandbox_command_desc: "Prevents harmful system commands from running.",
    sandbox_privilege_guard: "System Access Blocked",
    sandbox_privilege_desc: "Stops attempts to access system internals.",
    sandbox_provenance_check: "Creator Rating",
    sandbox_provenance_desc: "Checks that the creator has a good track record.",
    sandbox_available_templates: "Available Templates",
    sandbox_no_templates: "No templates available yet.",
    sandbox_intro_title: "What is the Test Area?",
    sandbox_intro_desc: "A safe place to test your AI agent's skills before publishing. Write a skill manifest (rules for your agent), and the sandbox will simulate how it runs — without affecting anything live.",
    sandbox_how_it_works: "How it works:",
    sandbox_step_1: "Write or edit the skill manifest on the left",
    sandbox_step_2: "Click \"Run Test\" to simulate execution",
    sandbox_step_3: "Watch the security scan and terminal output below",
    sandbox_manifest_label: "Skill Manifest",
    sandbox_manifest_hint: "This is the rulebook for your agent. Describe what it should do, its boundaries, and any special instructions.",
    sandbox_input_label: "Test Input",
    sandbox_input_hint: "Give your agent something to work with. This simulates a real request.",
    sandbox_security_title: "Safety Check",
    sandbox_security_desc: "Every skill is checked for safety before it can run. Green = safe.",
    // Marketplace page
    marketplace_title: "Skills Marketplace",
    marketplace_browse: "Back to Skills",
    marketplace_publish: "Share Your Skill",
    marketplace_search: "Search for skills...",
    marketplace_all: "ALL",
    marketplace_published: "Published Skills",
    marketplace_published_desc: "Skills available to install",
    marketplace_installs: "Total Installs",
    marketplace_installs_desc: "Times installed by users",
    marketplace_pro_skills: "Pro+ Skills",
    marketplace_pro_skills_desc: "Advanced premium skills",
    marketplace_free_skills: "Free Skills",
    marketplace_free_skills_desc: "No cost to install",
    marketplace_no_skills: "No Skills Available Yet",
    marketplace_publish_first: "Be the first to share a skill with the community! Skills let your agent do new things.",
    marketplace_publish_btn: "Share Your First Skill",
    marketplace_welcome_banner: "Welcome to the Skills Marketplace",
    marketplace_welcome_desc: "Browse and install skills to give your agent new abilities. Skills are safe, verified, and easy to add.",
    marketplace_no_desc: "No description available",
    marketplace_signed: "Verified & Signed",
    marketplace_free: "FREE",
    marketplace_load_more: "Load More",
    marketplace_close: "Close",
    marketplace_installs_label: "installs",
    marketplace_manifest: "What This Skill Does",
    marketplace_manifest_desc: "Here's how this skill works and what it lets your agent do:",
    marketplace_script: "How To Use It",
    marketplace_script_desc: "After installing, this skill will automatically run when your agent needs it. No setup required.",
    marketplace_test_suite: "TEST SUITE",
    marketplace_installing: "Installing...",
    marketplace_connecting: "Connecting...",
    marketplace_connect_install: "Connect Wallet to Add",
    marketplace_install_skill: "Add to My Agent",
    marketplace_copy_payload: "Copy Details",
    marketplace_dismiss: "Dismiss",
    marketplace_back_to_skills: "Back to Skills",
    // OnboardingModal
    onboarding_modal_title: "AGENT ONBOARDING",
    onboarding_modal_step_label: "Step {step} of 3",
    onboarding_modal_skip: "SKIP",
    onboarding_modal_connect_title: "Connect Your Pi Wallet",
    onboarding_modal_connect_desc: "Link your secure Pi cryptographic identity to anchor your autonomous agent.",
    onboarding_modal_pi_browser: "Open in Pi Browser",
    onboarding_modal_demo: "EXPLORE DEMO MODE",
    onboarding_modal_create_title: "Create Autonomous Agent",
    onboarding_modal_create_desc: "Define the name for your autonomous gRPC agent.",
    onboarding_modal_agent_name_placeholder: "Agent name (optional)",
    onboarding_modal_creating: "CREATING AGENT...",
    onboarding_modal_create_btn: "CREATE AGENT",
    onboarding_modal_ready_title: "Your Passport is Ready!",
    onboarding_modal_ready_desc: "Your agent identity passport has been successfully anchored.",
    onboarding_modal_agent_label: "Agent:",
    onboarding_modal_did_label: "DID:",
    onboarding_modal_get_started: "GET STARTED",
    // Docs page
    docs_sidebar_label: "Documentation",
    docs_search_placeholder: "Search docs...",
    docs_badge_core: "Core Protocol",
    docs_intro_title: "Introduction to AxiomID",
    docs_intro_desc: "AxiomID is a decentralized identity and human-authorization layer engineered to manage sybil-resistant agentic loops. By using W3C compliant Verifiable Credentials (VCs) and Decentralized Identifiers (DIDs), AxiomID allows humans to safely delegate transactional, computational, or social tasks to autonomous AI agents.",
    docs_did_title: "The did:axiom DID Method",
    docs_did_desc: "Each verified Pioneer generates a unique sovereign DID formatted as did:axiom:piUsername. This document is cryptographically resolved by our oracle network, binding public keys directly to ledger accounts.",
    docs_badge_trust: "Trust Engine",
    docs_stamps_title: "Identity Stamps",
    docs_stamps_desc: "Trust is verified via cryptographically signed stamps. Each stamp earns XP and increases your Trust Score, elevating your Identity Tier from Visitor → Citizen → Validator → Sovereign.",
    docs_stamp_kyc_name: "KYC Bound Stamp",
    docs_stamp_kyc_xp: "250 XP",
    docs_stamp_kyc_desc: "Anchors proof of Pi Network KYC verification without exposing personal data. This is the highest-trust stamp — proves you are a verified human on Pi Network.",
    docs_stamp_wallet_name: "Wallet Age Stamp",
    docs_stamp_wallet_xp: "100 XP",
    docs_stamp_wallet_desc: "Verifies the age and transaction history of your connected Stellar/Pi wallet. Older wallets with active history earn higher trust.",
    docs_stamp_social_name: "Social Identity Stamp",
    docs_stamp_social_xp: "100 XP each",
    docs_stamp_social_desc: "Validates ownership of Twitter, Discord, and Google accounts via cryptographic protocol signatures. Each social link is an independent stamp.",
    docs_stamp_tx_name: "Transaction Stamp",
    docs_stamp_tx_xp: "50 XP each",
    docs_stamp_tx_desc: "Proves on-chain activity through verified Pi or Stellar transactions. More transactions = higher trust signal.",
    docs_stamp_agent_name: "Agent Stamp",
    docs_stamp_agent_xp: "150 XP",
    docs_stamp_agent_desc: "Verifies that an AI agent is deployed, active, and working under your delegation. Ties agent behavior to your trust score.",
    docs_stamp_pow_name: "Daily PoW Proof",
    docs_stamp_pow_xp: "10 XP daily",
    docs_stamp_pow_desc: "Establishes daily active human participation through lightweight cryptographic proof-of-work tasks. Consistency builds trust.",
    docs_trust_formula_title: "Trust Score Formula",
    docs_trust_formula_desc: "XP Score = min(100, XP/10). Stamp Score = (stamps claimed / 6 total) × 100.",
    docs_badge_sdk: "Client Integration",
    docs_sdk_title: "SDK & Integration",
    docs_sdk_desc: "AxiomID provides two packages: `@axiomid/sdk` for querying trust/passport data, and `@axiomid/crypto` for Ed25519 key derivation and signing. Both are MIT licensed.",
    docs_sdk_packages_title: "Packages",
    docs_sdk_query_name: "@axiomid/sdk",
    docs_sdk_query_desc: "Query passports, trust scores, stamps, and DID documents",
    docs_sdk_crypto_name: "@axiomid/crypto",
    docs_sdk_crypto_desc: "Ed25519 key derivation, signing, and verification",
    docs_sdk_config_title: "@axiomid/sdk — Configuration",
    docs_sdk_api_title: "SDK API Reference",
    docs_sdk_api_verify: "Fetch public passport with trust score, tier, stamps, and agent status",
    docs_sdk_api_stamps: "Get all verified stamps for a user (KYC, wallet, social, agent)",
    docs_sdk_api_did: "Resolve a did:axiom identifier to its W3C DID document",
    docs_sdk_api_trust: "Get trust score breakdown: XP component + stamp component",
    docs_sdk_api_skills: "Search skills by name, description, or capabilities",
    docs_sdk_derive_title: "@axiomid/crypto — Key Derivation",
    docs_sdk_derive_desc: "Deterministic Ed25519 keypair derivation from Stellar address + agent ID. Server-side only (uses Node.js crypto).",
    docs_sdk_security_title: "Security Note",
    docs_sdk_security_desc: "`deriveKeypair` MUST use `SOVEREIGN_KEY_SALT` from env. Never use public inputs alone as key material. Private keys never leave the server.",
    docs_badge_api: "HTTP Reference",
    docs_api_title: "API Reference",
    docs_api_desc: "AxiomID exposes public read-only endpoints and authenticated write endpoints. All public endpoints are rate-limited.",
    docs_api_response_title: "Response Envelope",
    docs_api_openapi_title: "OpenAPI Specification",
    docs_api_openapi_desc: "Full OpenAPI 3.1 spec available at:",
    // Landing page
    landing_pi_badge: "Live on Pi Network Testnet",
    landing_headline_en: "Your Identity.",
    landing_headline_rules_en: "Your Rules.",
    landing_headline_ar: "هويتك.",
    landing_headline_rules_ar: "قوانينك.",
    landing_tagline: "No permission needed. One DID. Infinite agents. Cryptographic proof of human intent.",
    landing_watch_demo: "Watch the Demo",
    landing_how_it_works: "How It Works",
    landing_three_steps: "Three Steps to Agent Identity",
    landing_step1_title: "Connect",
    landing_step1_desc: "Link your Pi wallet or any Stellar address. Your identity starts here.",
    landing_step2_title: "Verify",
    landing_step2_desc: "Complete KYA + KYC. Build trust through social actions and on-chain activity.",
    landing_step3_title: "Deploy",
    landing_step3_desc: "Your Agent Passport is ready. Use it across the Pi ecosystem with Pi token payments only.",
    landing_sovereign_advantage: "The Sovereign Advantage",
    landing_why_title: "Why Choose AxiomID?",
    landing_web2_title: "Traditional Identity (Web2)",
    landing_web2_item1: "Siloed data: Your profiles are owned by third-party platforms.",
    landing_web2_item2: "High friction: Repeated manual KYC checks for every app.",
    landing_web2_item3: "Vulnerable: Easy spoofing of digital identities and usernames.",
    landing_web2_item4: "No AI integration: Machine agents cannot prove their authority.",
    landing_web2_result: "Result: Fragile security, high friction, no agent trust.",
    landing_axiom_title: "AxiomID Sovereign Passport",
    landing_axiom_item1: "Decentralized: You own your credentials via W3C DIDs.",
    landing_axiom_item2: "Verify once, prove everywhere: Single dashboard for all stamps.",
    landing_axiom_item3: "Cryptographic security: Trust Score verified on-chain.",
    landing_axiom_item4: "Agent-native: Built for AI agents to represent you securely.",
    landing_axiom_result: "Result: Frictionless auth, resilient trust, delegation-ready.",
    landing_level_up: "Level Up Your Identity",
    // Tier labels
    tier_basic_tool: "Basic Tool",
    tier_advanced_tool: "Advanced Tool",
    tier_advanced_infrastructure: "Infra",
    tier_pro: "Pro",
    tier_sovereign: "Sovereign",
  },
  ar: {
    // Navigation / Header
    nav_dashboard: "لوحة التحكم",
    dashboard_title: "لوحة تحكم AxiomID",
    nav_settings: "الإعدادات",
    nav_status: "حالة الشبكة",
    nav_privacy: "سياسة الخصوصية",
    nav_terms: "شروط الخدمة",
    nav_explorer: "مستكشف البروتوكول",
    nav_docs: "الوثائق التقنية",
    nav_about: "خريطة الطريق والتعريف",
    nav_leaderboard: "لوحة الترتيب العامة",
    nav_onboarding: "التسجيل التوجيهي",
    connect_wallet: "ربط محفظة Pi",
    disconnect_wallet: "قطع الاتصال",
    // Landing
    hero_title: "AxiomID",
    hero_heading: "هوية العملاء لعصر الذكاء الاصطناعي.",
    hero_desc: "جواز العميل اللامركزي القائم على المعرفات اللامركزية DIDs. تحقق مرة واحدة، وأثبت هويتك في كل مكان. هوية متوافقة مع معايير KYA و KYC للبشر وعملائهم الآليين.",
    hero_subtitle: "بروتوكول تفويض الهوية البشرية. توثيق الهوية اللامركزية للتعاون المشترك بين البشر والذكاء الاصطناعي.",
    hero_badge: "طبقة الهوية المؤمنة",
    btn_launch: "تشغيل لوحة التحكم",
    btn_explorer: "استكشاف البروتوكول",
    stat_agents: "العملاء المسجلون",
    stat_tx: "إجمالي العمليات",
    stat_trust: "معدل نقاط الثقة",
    stat_users: "المستخدمون النشطون",
    // Dashboard
    welcome: "مرحباً بك مجدداً",
    welcome_back: "مرحباً بك مجدداً",
    your_passport: "جواز العميل",
    xp_balance: "رصيد نقاط XP",
    trust_score: "نقاط الثقة",
    tier: "فئة الهوية",
    stamps_board: "طوابع الهوية",
    claim_stamp: "المطالبة بالطابع",
    stamps_desc: "قم بتوثيق حساباتك وروابطك للمطالبة بطوابع الهوية التشفيرية.",
    connected: "متصل",
    not_connected: "غير متصل",
    agent_stats: "إحصائيات العميل",
    skills: "المهارات",
    quick_links: "روابط سريعة",
    identity_verification_kya: "توثيق الهوية (KYA)",
    skills_marketplace: "سوق المهارات",
    marketplace: "سوق المهارات",
    sandbox: "بيئة الاختبار",
    create_your_agent: "أنشئ عميلك الآلي",
    agent_quick_actions: "إجراءات العميل السريعة",
    replay_onboarding: "إعادة عرض الترحيب",
    // Settings
    settings_title: "إعدادات البروتوكول",
    settings_desc: "إدارة المؤهلات التشفيرية، الحسابات المرتبطة، وتفاصيل الجواز الخاص بك.",
    linked_accounts: "المنصات المرتبطة",
    credential_vc: "الوثيقة القابلة للتحقق (VC)",
    view_vc: "عرض تفاصيل الوثيقة (VC)",
    close: "إغلاق",
    wallet_address: "عنوان المحفظة",
    did: "المعرف اللامركزي (DID)",
    system_appearance: "مظهر النظام",
    // Status
    status_title: "حالة الشبكة والعميل",
    status_desc: "مؤشرات حالة البروتوكول المباشرة ومقاييس توثيق العملاء.",
    operational: "يعمل بشكل طبيعي",
    system_all_good: "جميع الأنظمة تعمل بشكل طبيعي وآمن.",
    averages: "المعدلات والنسب",
    total_xp: "إجمالي نقاط XP المكتسبة",
    verification_rate: "نسبة توثيق الهوية الناجحة",
    // Onboarding
    onboarding_title_1: "بروتوكول AxiomID السيادي",
    onboarding_title_2: "AxiomID: بروتوكول الروح",
    onboarding_title_3: "جواز سفرك أصبح جاهزاً!",
    onboarding_desc_1: "أنشئ دليلك التشفيري السيادي على بشريتك. اربط حساباتك للحصول على نقاط ثقة وطوابع تشفيرية.",
    onboarding_desc_2: "قم بتفويض عملاء مستقلين لإجراء المعاملات نيابة عنك بحماية أمنية كاملة.",
    onboarding_desc_3: "المعرف اللامركزي (DID) وجواز العميل الخاص بك نشط الآن. أهلاً بك في جذر الثقة.",
    onboarding_step_1: "ربط المحفظة",
    onboarding_step_2: "إنشاء العميل",
    onboarding_step_3: "جاهز",
    onboarding_step_label: "الخطوة {step} من 4",
    onboarding_step1_title: "ربط المفتاح السيادي",
    onboarding_step1_desc: "أسس تفويض الهوية الرقمية عبر مفتاح شبكة Pi أو Stellar.",
    onboarding_step2_title: "إعداد العميل الذكي",
    onboarding_step2_desc: "امنح عميلك الآلي المستقل اسماً مميزاً للتعريف.",
    onboarding_step3_title: "توثيق الهوية والربط",
    onboarding_step3_desc: "اربح بيانات الاعتماد ومستندات DID لتأكيد هويتك.",
    onboarding_step4_title: "تم إصدار جواز السفر",
    onboarding_step4_desc: "جواز سفر العميل اللامركزي الخاص بك نشط ومسجل بالكامل.",
    onboarding_connect_desc: "قم بتفويض الوصول لجلب البيانات: معرف المستخدم، مفاتيح المحفظة، وإعدادات العقد النشطة.",
    onboarding_wallet_connected: "تم ربط المحفظة بنجاح.",
    onboarding_requesting_access: "جاري طلب الوصول عبر متصفح Pi...",
    onboarding_connect_wallet_btn: "ربط المحفظة",
    onboarding_agent_name_label: "اسم ممثل العميل",
    onboarding_agent_name_placeholder: "مثال: Sentinel-1",
    onboarding_provisioning: "جاري إعداد العميل...",
    onboarding_provision_btn: "إعداد العميل",
    onboarding_seal_desc: "الحصول على طابع بيانات الاعتماد الأساسي يتحقق من معايير KYA مباشرة لتأمين حدود تفويض الثقة.",
    onboarding_seal_verified: "تم التحقق من حل المعرف السيادي. جاهز للإغلاق.",
    onboarding_seal_btn: "إغلاق بيانات الجواز",
    onboarding_congrats_desc: "تهانينا يا رائد! ملف جوازك موثق وموقع تشفيرياً وقابل للنقل كمعيار did:axiom.",
    onboarding_enter_dashboard: "دخول لوحة التحكم",
    onboarding_back: "\u2190 السابق",
    onboarding_footer: "\u00a9 2026 بروتوكول AxiomID \u2022 معالج التسجيل السيادي",
    onboarding_agent_failed: "فشل في إعداد العميل. يرجى المحاولة مرة أخرى.",
    onboarding_state_prefix: "الحالة: ",
    onboarding_state_visitor: "زائر",
    onboarding_state_connected: "متصل",
    onboarding_state_partial_kyc: "KYC جزئي",
    onboarding_state_verified: "موثق",
    onboarding_state_pending_review: "قيد المراجعة",
    onboarding_state_error: "خطأ",
    onboarding_default_agent_name: "عميل AxiomID الرائد",
    header_back: "عودة",
    passport_locked_preview: "معاينة مقفلة",
    passport_anonymous: "رائد مجهول",
    next: "التالي",
    back: "السابق",
    finish: "ابدأ الآن",
    // General
    loading: "جاري تحميل الهوية التشفيرية...",
    visitor: "زائر",
    citizen: "مواطن",
    validator: "مدقق",
    sovereign: "سيادي",
    enter_dashboard: "دخول لوحة التحكم",
    logout: "تسجيل الخروج",
    connecting: "جاري الاتصال...",
    connect: "اتصال",
    claim_passport: "احصل على جوازك",
    open_dashboard: "افتح لوحة التحكم",
    read_docs: "الوثائق التقنية",
    backed_by_pi: "مدعوم من شبكة Pi",
    pioneers_joined: "الرواد المنضمين",
    agents_deployed: "العملاء النشطين",
    on_chain: "100% على السلسلة",
    tab_passport: "الجواز",
    tab_actions: "العمليات",
    tab_agent: "العميل",
    tab_terminal: "الطرفية",
    tab_marketplace: "السوق",
    ad_rewards_title: "إعلانات مكافأة PI",
    ad_rewards_desc: "شاهد إعلاناً قصيراً للحصول على 10 XP إضافية على الفور ورفع مستوى التوثيق الخاص بك.",
    ad_rewards_loading: "جاري التحميل...",
    ad_rewards_btn: "شاهد الإعلان (+10 XP)",
    watch_demo_title: "شاهد النظام عملياً",
    watch_demo_desc: "شاهد كيف ينشئ AxiomID هويتك السيادية في ثوانٍ.",
    quick_stats: "إحصائيات سريعة",
    days_active: "أيام النشاط",
    recent_activity: "النشاط الأخير",
    actions_count: "العمليات",
    trust_score_label: "نقاط الثقة",
    xp_progress: "تقدم الخبرة",
    agent_status: "حالة العميل",
    no_activity: "لا توجد نشاطات حديثة",
    // Pi Browser prompts
    pi_browser_required: "قم بالاتصال عبر متصفح Pi لفتح هويتك الرقمية",
    // Passport & Components
    agent_passport: "جواز العميل",
    no_address: "لا يوجد عنوان",
    label_wallet: "المحفظة",
    label_agent: "العميل",
    status_none: "لا شيء",
    tier_label: "الفئة",
    label_trust: "الثقة",
    label_xp: "نقاط XP",
    label_issued: "صادر",
    kya_manifest: "بيان KYA",
    manifest_principal: "المسؤول:",
    manifest_network: "الشبكة:",
    pi_network: "شبكة Pi",
    manifest_kyc_bound: "مرتبط بـ KYC:",
    manifest_license: "الرخصة:",
    passport_footer_verified: "موثق من AxiomID • هوية متوافقة مع Pi",
    trust_score_desc: "اجمع الطوابع لبناء نقاط ثقة تشفيرية.",
    stamps_label: "الطوابع:",
    level_progress: "تقدم المستوى",
    current_tier: "الفئة الحالية:",
    percent_complete: "% مكتمل",
    next_tier: "الفئة التالية:",
    xp_needed: "نقاط XP مطلوبة",
    live_stamps_collection: "مجموعة الطوابع المباشرة",
    stamps_collection_desc: "أكمل المهام لتقسيم بيانات اعتماد قابلة للتحقق",
    w3c_vc_title: "وثيقة اعتماد W3C القابلة للتحقق",
    w3c_vc_subtitle: "مطالبة موقعة تشفيرياً",
    copied: "تم النسخ!",
    copy_payload: "نسخ المحتوى",
    download_json: "تحميل JSON",
    verified: "موثق",
    reward_label: "المكافأة:",
    claimed: "تم المطالبة",
    inspect_vc: "فحص الوثيقة",
    placeholder_email: "البريد الإلكتروني",
    placeholder_username: "اسم المستخدم",
    claiming: "جاري المطالبة...",
    submit: "إرسال",
    cancel: "إلغاء",
    connect_profile: "ربط الحساب",
    score_excellent: "ممتاز",
    score_strong: "قوي",
    score_moderate: "متوسط",
    score_low: "منخفض",
    score_new: "جديد",
    status_verified: "موثق",
    status_pending: "قيد المراجعة",
    status_unverified: "غير موثق",
    status_denied: "مرفوض",
    passport_not_found: "جواز السفر غير موجود",
    passport_not_found_description: "هذا الجواز غير موجود أو تمت إزالته.",
    passport_load_error: "فشل تحميل الجواز",
    something_went_wrong: "حدث خطأ ما",
    try_again: "حاول مرة أخرى",
    signin_failed: "فشل تسجيل الدخول",
    completing_sign_in: "جاري إكمال تسجيل الدخول...",
    create_your_passport: "أنشئ جواز سفرك",
    link_copied: "تم نسخ الرابط!",
    share_passport: "مشاركة الجواز",
    export_image: "تصدير كصورة",
    mint_sbt: "إصدار كـ SBT",
    mint_success: "تم إصدار Soulbound Token بنجاح على Stellar!",
    passport_verified_by: "هذا الجواز موثق من بروتوكول AxiomID",
    passport_export_failed: "فشل تصدير صورة الجواز. حاول مرة أخرى.",
    share_title: "جواز العميل AxiomID",
    share_text: "تحقق من جواز العميل AxiomID الموثق الخاص بي!",
    vc_no_data: "لا توجد بيانات وثيقة قابلة للتحقق لهذا الطابع.",
    vc_empty_metadata: "بيانات الوثيقة فارغة.",
    vc_parse_error: "فشل في تحليل بيانات الوثيقة القابلة للتحقق.",
    yes: "نعم",
    no: "لا",
    settings_sovereign_title: "إعدادات السيادة",
    settings_wallet_prompt: "يرجى ربط محفظتك للوصول إلى تفاصيل الملف الشخصي وربط الحسابات.",
    settings_back_landing: "← العودة إلى الصفحة الرئيسية",
    settings_page_title: "إعدادات AxiomID",
    settings_page_desc: "إدارة المفاتيح السيادية والاتصالات",
    settings_dashboard_link: "← لوحة التحكم",
    settings_profile_title: "ملفك الشخصي",
    settings_pi_network_id: "معرف شبكة Pi",
    settings_stellar_wallet: "محفظة Stellar",
    settings_sovereign_did: "معرفك الفريد",
    settings_copy: "نسخ",
    authenticated_pioneer: "رائد موثق",
    settings_identity_status: "حالة الهوية",
    settings_verified_human: "إنسان موثق",
    settings_pending_kyc: "في انتظار التحقق",
    settings_progression_title: "تقدمك",
    settings_social_title: "الحسابات المتصلة",
    settings_xp_reward: "مكافأة XP:",
    settings_connect_btn: "اتصال",
    settings_ledger_title: "سجل النشاط",
    settings_ledger_empty_helper: "قم بتوصيل الحسابات أو احصل على الطوابع لرؤية النشاط هنا.",
    settings_disconnect_btn: "فصل الاتصال",
    settings_no_tx: "لا يوجد نشاط بعد. ستظهر إجراءاتك هنا أثناء استخدام AxiomID.",
    settings_tx_objective: "الهدف",
    settings_balance_shift: "تغير الرصيد",
    settings_timestamp: "الوقت",
    settings_link_profile: "ربط حساب {platform}",
    settings_link_desc: "اكتب اسم المستخدم لربط هذا الحساب. هذا ينشئ رابطاً موثقاً يثبت أنك تملك كلا الحسابين.",
    settings_link_handle_label: "اسم المستخدم",
    settings_link_email_label: "البريد الإلكتروني",
    settings_link_email_placeholder: "name@gmail.com",
    settings_link_placeholder: "@cryptojoker",
    settings_signing: "جاري التوقيع...",
    settings_confirm_claim: "تأكيد المطالبة",
    settings_vc_title: "SocialIdentityCredential (معيار W3C)",
    settings_vc_desc: "موقع من سلطة إصدار AxiomID. انسخ المحتوى للتحقق من قابلية النقل.",
    settings_profile_helper: "هذا كيف يراك الآخرون على AxiomID. عنوان محفظتك ومعرفك الفريد هو هويتك.",
    settings_progression_helper: "اكسب XP بإكمال المهام وربط الحسابات واستخدام عميلك. الفئات الأعلى تفتح مزيداً من الميزات.",
    settings_social_helper: "ربط الحسابات يساعد في إثبات أنك شخص حقيقي ويكسبك XP. كل اتصال ينشئ إثباتاً تشفيرياً.",
    settings_ledger_helper: "سجل لجميع إجراءاتك على AxiomID. كل مطالبة طابع وربط حساب وتثبيت مهارة مسجل هنا.",
    settings_danger_zone: "منطقة الخطر",
    settings_danger_desc: "هذه الإجراءات دائمة ولا يمكن التراجع عنها.",
    settings_export_data: "تصدير البيانات",
    settings_export_desc: "تحميل نسخة من بيانات جوازك وطوابعك وسجل النشاط بصيغة JSON.",
    settings_export_btn: "تصدير JSON",
    settings_sidebar_profile: "الملف الشخصي",
    settings_sidebar_accounts: "الحسابات المتصلة",
    settings_sidebar_ledger: "سجل XP",
    settings_sidebar_settings: "الإعدادات",
    settings_confirm_title: "هل أنت متأكد؟",
    settings_confirm_disconnect: "سيؤدي هذا إلى قطع اتصال حساب {platform} الخاص بك. ستفقد نقاط XP من هذا الاتصال.",
    settings_confirm_action: "تأكيد",
    settings_confirm_cancel: "إلغاء",
    settings_disconnecting: "جاري قطع الاتصال...",
    settings_vc_copied: "تم نسخ بيانات الوثيقة إلى الحافظة",
    settings_disconnect_failed: "فشل قطع اتصال الحساب",
    settings_progress_label: "التقدم",
    settings_max_level: "تم بلوغ المستوى الأقصى",
    settings_xp_needed: "نقاط XP مطلوبة",
    // Dashboard Showcase Mode
    showcase_title: "وضع العرض",
    showcase_desc: "قم بإنشاء رابط تفويض آمن بين البشر والذكاء الاصطناعي. بمجرد المصادقة داخل متصفح Pi، يفتح لوحة التحكم هذه حماية المعاملات في الوقت الفعلي والأوراكلات المباشرة وربط الطوابع الاجتماعية.",
    // Marketplace toasts / errors
    marketplace_install_success: "تم تثبيت المهارة بنجاح",
    marketplace_need_agent: "أنشئ عميلاً قبل شراء المهارات",
    // Dashboard Components
    welcome_back_name: "مرحباً بك مجدداً، {username}",
    agent_identity_ready: "هوية عميلك جاهزة. المستوى",
    stat_level: "المستوى",
    stat_xp: "نقاط XP",
    stat_agent: "العميل",
    agent_trust_label: "الثقة",
    stat_status: "الحالة",
    no_skills_installed: "لا توجد مهارات مثبتة",
    kya_secure_did: "أمنت مستند DID الخاص بك من خلال التحقق من بياناتك.",
    kya_verified_anchored: "✓ تم توثيق AxiomID",
    kya_identity_verified: "تم التحقق من هويتك وتوثيقها بشكل دائم تحت المعرف:",
    kya_verification_pending: "التوثيق معلق",
    kya_oracle_validating: "شبكة الأوراكل تتحقق من بياناتك. سيتم فتح المهام المتقدمة بعد الموافقة.",
    kya_pi_username: "اسم مستخدم Pi",
    kya_verifying: "جاري التوثيق...",
    kya_verify_identity: "توثيق KYC",
    agent_id_label: "معرف العميل:",
    agent_xp_label: "نقاط XP",
    agent_last_active: "آخر نشاط",
    agent_never_active: "لم يكن نشطاً",
    agent_activating: "جاري التنشيط...",
    agent_activate: "تنشيط",
    agent_pausing: "جاري الإيقاف المؤقت...",
    agent_pause: "إيقاف مؤقت",
    agent_resuming: "جاري الاستئناف...",
    agent_resume: "استئناف",
    terminal_title: "الطرفية",
    terminal_entries: "سجلات",
    terminal_clear: "مسح",
    terminal_run_test: "تشغيل اختبار",
    terminal_waiting: "في انتظار نشاط المحفظة...",
    view_passport: "عرض الجواز",
    did_document: "مستند DID",
    create_agent_title: "أنشئ عميلك",
    create_agent_desc: "أعطِ عميلك اسماً للبدء.",
    create_agent_tier_info: "سيبدأ عميلك من الفئة 1 مع 0 نقطة XP ويمكن تنشيطه في أي وقت.",
    create_agent_placeholder: "اسم العميل (اختياري)",
    create_agent_creating: "جاري الإنشاء...",
    create_agent_create: "إنشاء",
    // Privacy page
    privacy_legal: "قانوني",
    privacy_last_updated: "آخر تحديث: 17 مايو 2026",
    privacy_title: "الخصوصية",
    privacy_title_gradient: "الخاصة",
    privacy_subtitle: "كيف تتعامل AxiomID مع بياناتك.",
    privacy_info_collect: "المعلومات التي نجمعها",
    privacy_info_collect_desc: "عند توصيل محفظتك عبر Pi Network، نجمع عنوان محفظة Pi ورقم Pi Network UID الخاص بك لأغراض المصادقة وتتبع نقاط XP. لا نجمع أي معلومات تعريف شخصية مثل اسمك أو بريدك الإلكتروني أو عنوان IP الخاص بك بخلاف سجلات الخادم القياسية.",
    privacy_how_use: "كيف نستخدم المعلومات",
    privacy_how_use_desc: "نستخدم عنوان محفظتك ورقم Pi UID فقط لتشغيل التطبيق وتتبع نقاط السمعة (XP/Tier) وتمكين التحقق من وكيل الذكاء الاصطناعي. لا تُباع بياناتك أبداً ولا تُشارك مع أطراف ثالثة. قد تُستخدم التحليلات المجمعة المجهولة الهوية لتحسين المنصة.",
    privacy_data_storage: "تخزين البيانات والأمان",
    privacy_data_storage_desc: "يتم تخزين بياناتك بشكل آمن في قاعدة بيانات PostgreSQL على بنية Ghost. نستخدم تشفيراً متصلاً ومعيار الصناعة أثناء النقل. يمكنك طلب حذف بياناتك في أي وقت عن طريق الاتصال بنا عبر GitHub.",
    privacy_rights: "حقوقك",
    privacy_rights_desc: "لديك الحق في الوصول إلى بياناتك أو تصحيحها أو حذفها. لممارسة هذه الحقوق، افتح مشكلة على مستودع GitHub الخاص بنا أو تواصل مع المطور مباشرة.",
    // Terms page
    terms_legal: "قانوني",
    terms_last_updated: "آخر تحديث: 17 مايو 2026",
    terms_title: "شروط الخدمة",
    terms_title_main: "شروط",
    terms_title_highlight: "الخدمة",
    terms_subtitle: "باستخدام AxiomID، أنت توافق على هذه الشروط.",
    terms_use: "استخدام الخدمة",
    terms_use_desc: "توفر AxiomID التحقق من الهوية اللامركزية ونقاط السمعة. يمكنك استخدام الخدمة بجميع القوانين واللوائح المعمول بها. تُقدم الخدمة لأغراض مشروعة فقط.",
    terms_wallet: "توصيل المحفظة",
    terms_wallet_desc: "توصيل محفظة Pi مطلوب للمصادقة. أنت مسؤول وحيد عن أمان محفظتك ومفاتيحك الخاصة. ليس لدى AxiomID الوصول إلى مفاتيحك الخاصة أو عبارات البذور.",
    terms_ai_agent: "تحقق وكيل الذكاء الاصطناعي",
    terms_ai_agent_desc: "يمكن لكل مستخدم تسجيل وكيل ذكاء اصطناعي واحد موثوق. يمكن للوكيل الموثوق التفاعل مع منتجات النظام البيئي نيابةً عنك. أنت مسؤول عن جميع إجراءات الوكيل. التحقق من الوكيل غير قابل للنقل.",
    terms_liability: "تحديد المسؤولية",
    terms_liability_desc: "يتم تقديم التطبيق \"كما هو\" دون أي ضمانات من أي نوع، سواء صريحة أو ضمنية. لسنا مسؤولين عن أي أضرار ناتجة عن استخدام الخدمة أو عدم القدرة على استخدامها، بما في ذلك على سبيل المثال لا الحصر فقدان نقاط السمعة أو بيانات الوكيل أو معاملات Pi.",
    terms_changes: "تغييرات على الشروط",
    terms_changes_desc: "قد نقوم بتحديث هذه الشروط في أي وقت. يُعتبر استخدام الخدمة بعد التغييرات قبولاً للشروط الجديدة. سيتم إبلاغك بالتغييرات الجوهرية عبر التطبيق.",
    // Status page
    status_network_title: "حالة الشبكة",
    status_network_desc: "مراقبة في الوقت الفعلي لبروتوكول AxiomID وشبكة الوكلاء",
    status_retry: "إعادة المحاولة",
    status_registered_agents: "العملاء الموثقون",
    status_active_onchain: "الأشخاص الذين انضموا للشبكة",
    status_total_transactions: "المدفوعات",
    status_pi_payments: "مدفوعات Pi المعالجة بأمان",
    status_avg_trust: "ثقة المجتمع",
    status_network_safety: "مدى ثقة المجتمع بالشبكة",
    status_active_agents: "متصلون الآن",
    status_executing_loops: "العملاء النشطون حالياً",
    status_total_xp: "النقاط المكتسبة",
    status_accumulated: "إجمالي نقاط السمعة المحصّلة",
    status_verification_rate: "نجاح التوثيق",
    status_kyc_index: "نسبة المستخدمين الذين نجحوا في التحقق",
    status_protocol_details: "معلومات الشبكة",
    status_network: "الشبكة",
    status_version: "الإصدار",
    status_refreshed: "تم التحديث",
    status_ago: " ثانية",
    status_service_health: "حالة النظام",
    status_uptime: "وقت التشغيل",
    status_manifest_api: "هوية العميل",
    status_manifest_desc: "كل عميل يملك بطاقة هوية عامة. يمكنك البحث عن ملف أي عميل موثق باستخدام اسم المستخدم.",
    status_get: "GET",
    status_unable_load: "تعذر تحميل الحالة",
    status_could_not_fetch: "تعذر جلب إحصائيات الشبكة. يرجى المحاولة مرة أخرى لاحقاً.",
    status_no_data: "لا توجد بيانات بعد",
    status_no_data_desc: "ستظهر إحصائيات الشبكة هنا بمجرد انضمام العملاء.",
    // Sandbox page
    sandbox_title: "منطقة الاختبار",
    sandbox_active: "التجريب نشط",
    sandbox_idle: "المحرك في وضع الراحة",
    sandbox_edit_manifest: "تعديل القواعد",
    sandbox_ast_preview: "معاينة البنية",
    sandbox_yaml_md: "تنسيق القواعد",
    sandbox_syntax_tree: "عرض البنية",
    sandbox_input_payload: "بيانات الاختبار",
    sandbox_parameters: "المعاملات",
    sandbox_running: "جاري تشغيل المحاكاة...",
    sandbox_run_test: "تشغيل الاختبار",
    sandbox_copy_payload: "نسخ الحمولة",
    sandbox_terminal_output: "النتائج",
    sandbox_waiting: "انقر \"تشغيل الاختبار\" لرؤية النتائج هنا",
    sandbox_security_scan: "فحص الأمان",
    sandbox_pending: "قيد الانتظار",
    sandbox_scanning: "جاري الفحص",
    sandbox_passed: "نجح",
    sandbox_failed: "فشل",
    sandbox_sandbox_isolation: "بيئة آمنة",
    sandbox_sandbox_desc: "يعمل في حاوية معزولة وآمنة.",
    sandbox_ast_analysis: "فحص البنية",
    sandbox_ast_desc: "يفحص المحتوى الضار في قواعدك.",
    sandbox_injection_guard: "سلامة المدخلات",
    sandbox_injection_desc: "يتأكد من أن المدخلات لا يمكنها كسر النظام.",
    sandbox_signature_anchor: "المبتكر موثق",
    sandbox_signature_desc: "يؤكد هوية المبتكر.",
    sandbox_exfil_scan: "أمان الشبكة",
    sandbox_exfil_desc: "يحجب أي مشاركة بيانات غير مصرح بها.",
    sandbox_command_block: "الأوامر الخطرة محجوبة",
    sandbox_command_desc: "يمنع تنفيذ أوامر النظام الضارة.",
    sandbox_privilege_guard: "الوصول للنظام محجوب",
    sandbox_privilege_desc: "يوقف محاولات الوصول إلى ملفات النظام الداخلية.",
    sandbox_provenance_check: "تصنيف المبتكر",
    sandbox_provenance_desc: "يتحقق من أن المبتكر لديه سجل جيد.",
    sandbox_available_templates: "القوالب المتاحة",
    sandbox_no_templates: "لا توجد قوالب متاحة بعد.",
    sandbox_intro_title: "ما هي منطقة الاختبار؟",
    sandbox_intro_desc: "مكان آمن لاختبار مهارات وكيل الذكاء الاصطناعي الخاص بك قبل النشر. اكتب بيان المهارة (قواعد لوكيلك)، وستحاكي البيئة كيف يعمل — دون التأثير على أي شيء مباشر.",
    sandbox_how_it_works: "كيف يعمل:",
    sandbox_step_1: "اكتب أو عدّل بيان المهارة على اليسار",
    sandbox_step_2: "انقر \"تشغيل الاختبار\" لمحاكاة التنفيذ",
    sandbox_step_3: "شاهد فحص الأمان ومخرجات الطرفية أدناه",
    sandbox_manifest_label: "بيان المهارة",
    sandbox_manifest_hint: "هذا دليل القواعد لوكيلك. صف ما يجب أن يفعله وحدوده وأي تعليمات خاصة.",
    sandbox_input_label: "إدخال الاختبار",
    sandbox_input_hint: "أعطِ وكيلك شيئاً للعمل معه. هذا يحاكي طلباً حقيقياً.",
    sandbox_security_title: "فحص الأمان",
    sandbox_security_desc: "يتم فحص كل مهارة للسلامة قبل أن تتمكن من التشغيل. أخضر = آمن.",
    // Marketplace page
    marketplace_title: "سوق المهارات",
    marketplace_browse: "العودة إلى المهارات",
    marketplace_publish: "شارك مهارتك",
    marketplace_search: "ابحث عن مهارات...",
    marketplace_all: "الكل",
    marketplace_published: "المهارات المنشورة",
    marketplace_published_desc: "مهارات متاحة للتثبيت",
    marketplace_installs: "إجمالي التثبيتات",
    marketplace_installs_desc: "عدد مرات التثبيت من المستخدمين",
    marketplace_pro_skills: "المهارات الاحترافية+",
    marketplace_pro_skills_desc: "مهارات متقدمة مميزة",
    marketplace_free_skills: "المهارات المجانية",
    marketplace_free_skills_desc: "بدون تكلفة للتثبيت",
    marketplace_no_skills: "لا توجد مهارات متاحة بعد",
    marketplace_publish_first: "كن أول من يشارك مهارة مع المجتمع! المهارات تمنح عميلك قدرات جديدة.",
    marketplace_publish_btn: "شارك مهارتك الأولى",
    marketplace_welcome_banner: "مرحباً بك في سوق المهارات",
    marketplace_welcome_desc: "تصفح وتثبيت المهارات لإعطاء عميلك قدرات جديدة. المهارات آمنة وموثقة وسهلة الإضافة.",
    marketplace_no_desc: "لا يوجد وصف متاح",
    marketplace_signed: "موثق وموقّع",
    marketplace_free: "مجاني",
    marketplace_load_more: "تحميل المزيد",
    marketplace_close: "إغلاق",
    marketplace_installs_label: "التثبيتات",
    marketplace_manifest: "ماذا تفعل هذه المهارة",
    marketplace_manifest_desc: "إليك كيف تعمل هذه المهارة وما تفعله لعميلك:",
    marketplace_script: "كيفية الاستخدام",
    marketplace_script_desc: "بعد التثبيت، ستعمل هذه المهارة تلقائياً عندما يحتاج عميلك إليها. لا يتطلب أي إعداد.",
    marketplace_test_suite: "مجموعة الاختبارات",
    marketplace_installing: "جاري التثبيت...",
    marketplace_connecting: "جاري الاتصال...",
    marketplace_connect_install: "توصيل المحفظة للإضافة",
    marketplace_install_skill: "إضافة إلى عميلي",
    marketplace_copy_payload: "نسخ التفاصيل",
    marketplace_dismiss: "إغلاق",
    marketplace_back_to_skills: "العودة إلى المهارات",
    // OnboardingModal
    onboarding_modal_title: "تسجيل العميل",
    onboarding_modal_step_label: "الخطوة {step} من 3",
    onboarding_modal_skip: "تخطي",
    onboarding_modal_connect_title: "اربط محفظة Pi",
    onboarding_modal_connect_desc: "اربط هويتك التشفيرية الآمنة من Pi لتأسيس عميلك المستقل.",
    onboarding_modal_pi_browser: "افتح في متصفح Pi",
    onboarding_modal_demo: "استكشف وضع العرض التوضيحي",
    onboarding_modal_create_title: "إنشاء عميل مستقل",
    onboarding_modal_create_desc: "حدد اسم عميل gRPC المستقل.",
    onboarding_modal_agent_name_placeholder: "اسم العميل (اختياري)",
    onboarding_modal_creating: "جاري إنشاء العميل...",
    onboarding_modal_create_btn: "إنشاء العميل",
    onboarding_modal_ready_title: "جواز سفرك جاهز!",
    onboarding_modal_ready_desc: "تم تأسيس جواز هوية عميلك بنجاح.",
    onboarding_modal_agent_label: "العميل:",
    onboarding_modal_did_label: "المعرف:",
    onboarding_modal_get_started: "ابدأ الآن",
    // Docs page
    docs_sidebar_label: "الوثائق التقنية",
    docs_search_placeholder: "ابحث في الوثائق...",
    docs_badge_core: "بروتوكول أساسي",
    docs_intro_title: "مقدمة عن AxiomID",
    docs_intro_desc: "AxiomID طبقة هوية لامركزية وتفويض بشري مصممة لإدارة حلقات عملاء مقاومة للتزوير. باستخدام بيانات اعتماد يمكن التحقق منها المتوافقة مع W3C والمعرفات اللامركزية (DIDs)، تسمح AxiomID للبشر بتفويض المهام بشكل آمن لعملاء الذكاء الاصطناعي المستقلين.",
    docs_did_title: "طريقة did:axiom DID",
    docs_did_desc: "كل رائد موثّق يولّد معرفاً سيادياً فريداً بصيغة did:axiom:piUsername. يتم حل هذه الوثيقة تشفيرياً من شبكة الأوراكل الخاصة بنا، مما يربط المفاتيح العامة مباشرةً بحسابات السجل.",
    docs_badge_trust: "محرك الثقة",
    docs_stamps_title: "طوابع الهوية",
    docs_stamps_desc: "يتم التحقق من الثقة عبر طوابع موقعة تشفيرياً. كل طابع يكسب نقاط XP ويزيد من نقاط الثقة، مما يرفع مستوى الهوية من زائر → مواطن → مدقق → سيادي.",
    docs_stamp_kyc_name: "طابع KYC",
    docs_stamp_kyc_xp: "250 نقطة",
    docs_stamp_kyc_desc: "يثبت التحقق من KYC على شبكة Pi بدون الكشف عن البيانات الشخصية. هذا أعلى طابع ثقة — يثبت أنك إنسان موثّق.",
    docs_stamp_wallet_name: "طابع عمر المحفظة",
    docs_stamp_wallet_xp: "100 نقطة",
    docs_stamp_wallet_desc: "يتحقق من عمر محفظتك وسجل المعاملات. المحافظ الأقدم مع نشاط أعلى تكسب ثقة أعلى.",
    docs_stamp_social_name: "طابع الهوية الاجتماعية",
    docs_stamp_social_xp: "100 نقطة لكل طابع",
    docs_stamp_social_desc: "يتحقق من ملكية حسابات Twitter وDiscord وGoogle عبر توقيعات بروتوكول تشفيرية. كل رابط اجتماعي طابع مستقل.",
    docs_stamp_tx_name: "طابع المعاملات",
    docs_stamp_tx_xp: "50 نقطة لكل طابع",
    docs_stamp_tx_desc: "يثبت النشاط على السلسلة عبر معاملات Pi أو Stellar موثقة. المزيد من المعاملات = إشارة ثقة أعلى.",
    docs_stamp_agent_name: "طابع العميل",
    docs_stamp_agent_xp: "150 نقطة",
    docs_stamp_agent_desc: "يتحقق من أن عميل الذكاء الاصطناعي نشط ويعمل تحت تفويضك. يربط سلوك العميل بنقاط ثقتك.",
    docs_stamp_pow_name: "إثبات العمل اليومي",
    docs_stamp_pow_xp: "10 نقاط يومياً",
    docs_stamp_pow_desc: "يثبت المشاركة البشرية النشطة يومياً عبر مهام إثبات عمل تشفيرية خفيفة. الاتساق يبني الثقة.",
    docs_trust_formula_title: "صيغة نقاط الثقة",
    docs_trust_formula_desc: "نقاط XP = min(100, XP/10). نقاط الطوابع = (الطوابع المكتسبة / 6) × 100.",
    docs_badge_sdk: "تكامل العميل",
    docs_sdk_title: "مكتبة المطورين والدمج",
    docs_sdk_desc: "توفر AxiomID حزمتين: `@axiomid/sdk` للاستعلام عن بيانات الثقة والجواز، و`@axiomid/crypto` لاشتقاق مفاتيح Ed25519 والتوقيع. كلاهما بترخيص MIT.",
    docs_sdk_packages_title: "الحزم",
    docs_sdk_query_name: "@axiomid/sdk",
    docs_sdk_query_desc: "الاستعلام عن الجوازات ونقاط الثقة والطوابع ووثائق DID",
    docs_sdk_crypto_name: "@axiomid/crypto",
    docs_sdk_crypto_desc: "اشتقاق مفاتيح Ed25519 والتوقيع والتحقق",
    docs_sdk_config_title: "تكوين @axiomid/sdk",
    docs_sdk_api_title: "مرجع API لـ SDK",
    docs_sdk_api_verify: "جلب الجواز العام مع نقاط الثقة والمستوى والطوابع وحالة العميل",
    docs_sdk_api_stamps: "الحصول على جميع الطوابع الموثقة لمستخدم",
    docs_sdk_api_did: "حل معرف did:axiom إلى وثيقة W3C DID",
    docs_sdk_api_trust: "الحصول على تفاصيل نقاط الثقة: مكون XP + مكون الطوابع",
    docs_sdk_api_skills: "البحث عن مهارات بالاسم أو الوصف أو القدرات",
    docs_sdk_derive_title: "اشتقاق المفاتيح — @axiomid/crypto",
    docs_sdk_derive_desc: "اشتقاق مفتاح Ed25519 تحديدي من عنوان Stellar + معرف العميل. على الخادم فقط (يستخدم crypto في Node.js).",
    docs_sdk_security_title: "ملاحظة أمنية",
    docs_sdk_security_desc: "يجب أن يستخدم `deriveKeypair` مفتاح `SOVEREIGN_KEY_SALT` من متغيرات البيئة. لا تستخدم المدخلات العامة بمفردها كمفتاح. المفاتيح الخاصة لا تغادر الخادم أبداً.",
    docs_badge_api: "مرجع HTTP",
    docs_api_title: "مرجع واجهة البرمجة",
    docs_api_desc: "توفر AxiomID نقاط نهاية عامة للقراءة فقط ونقاط نهاية مصادقة للكتابة. جميع النقاط العامة مقيّدة المعدل.",
    docs_api_response_title: "مغلف الاستجابة",
    docs_api_openapi_title: "مواصفة OpenAPI",
    docs_api_openapi_desc: "مواصفة OpenAPI 3.1 كاملة متاحة على:",
    // Landing page
    landing_pi_badge: "مباشر على شبكة Pi التجريبية",
    landing_headline_en: "هويتك.",
    landing_headline_rules_en: "قوانينك.",
    landing_headline_ar: "هويتك.",
    landing_headline_rules_ar: "قوانينك.",
    landing_tagline: "بدون تصريح. هوية واحدة. عملاء لا نهائية. إثبات تشفيري لنية البشر.",
    landing_watch_demo: "شاهد العرض",
    landing_how_it_works: "كيف يعمل النظام؟",
    landing_three_steps: "ثلاث خطوات لبناء هوية العميل",
    landing_step1_title: "الاتصال",
    landing_step1_desc: "اربط محفظتك للبدء فوراً في تأسيس هويتك الرقمية.",
    landing_step2_title: "التحقق",
    landing_step2_desc: "أكمل خطوات التوثيق (KYA) واربح طوابع الهوية الرقمية.",
    landing_step3_title: "التشغيل",
    landing_step3_desc: "جواز سفر العميل الخاص بك جاهز للاستخدام في نظام Pi البيئي مع مدفوعات Pi فقط.",
    landing_sovereign_advantage: "الميزة السيادية",
    landing_why_title: "لماذا تختار AxiomID؟",
    landing_web2_title: "الهوية التقليدية (Web2)",
    landing_web2_item1: "بيانات معزولة: ملفاتك الشخصية مملوكة لمنصات خارجية.",
    landing_web2_item2: "خطوات معقدة: فحوصات KYC متكررة لكل تطبيق.",
    landing_web2_item3: "سهل الاختراق: انتحال سهل للهويات الرقمية وأسماء المستخدمين.",
    landing_web2_item4: "لا تكامل مع الذكاء الاصطناعي: لا يمكن للعملاء الآليين إثبات هويتهم.",
    landing_web2_result: "النتيجة: أمان هش، خطوات معقدة، غياب للثقة.",
    landing_axiom_title: "جواز السفر السيادي AxiomID",
    landing_axiom_item1: "لامركزي: أنت تمتلك بياناتك عبر W3C DIDs.",
    landing_axiom_item2: "تحقق مرة، أثبت في كل مكان: لوحة تحكم واحدة لجميع طوابعك.",
    landing_axiom_item3: "حماية تشفيرية: نقاط الثقة موثقة ومعتمدة رياضياً.",
    landing_axiom_item4: "مصمم للذكاء الاصطناعي: يمثلك عميلك الآلي بأمان.",
    landing_axiom_result: "النتيجة: مصادقة خالية من الاحتكاك، ثقة مرنة، تفويض آمن.",
    landing_level_up: "ارفع مستوى هويتك الرقمية",
    // Tier labels
    tier_basic_tool: "أداة أساسية",
    tier_advanced_tool: "أداة متقدمة",
    tier_advanced_infrastructure: "بنية تحتية",
    tier_pro: "محترف",
    tier_sovereign: "سيادي",
  }
};

type TranslationsKey = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationsKey | string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

/**
 * Provides language selection, persistence, and a translation helper to descendant components.
 *
 * Persists the chosen language to localStorage under `aix_language` and updates
 * `document.documentElement.dir` and `document.documentElement.lang` after initial mount.
 *
 * @param children - React nodes that will receive the language context
 * @returns A React context provider that supplies `{ language, setLanguage, t }` to its descendants
 */
export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === "undefined") return "en";
    const saved = localStorage.getItem("aix_language") as Language;
    return saved === "en" || saved === "ar" ? saved : "en";
  });
  const mountedRef = useRef(false);

  useEffect(() => {
    mountedRef.current = true;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("aix_language", lang);
  }, []);

  const t = useCallback((key: string): string => {
    const dict = translations[language] || translations.en;
    return (dict as Record<string, string>)[key] || key;
  }, [language]);

  const value = React.useMemo(
    () => ({ language, setLanguage, t }),
    [language, setLanguage, t]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

/**
 * Access the language context value for the current React tree.
 *
 * @returns The context object with `language`, `setLanguage`, and `t` (translation) helpers.
 * @throws Error if called outside a `LanguageProvider` (message: "useLanguage must be used within a LanguageProvider").
 */
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
